/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.quartz.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzFiredTriggers implements Serializable {

    private static final long serialVersionUID = 507107934;

    private String  schedName;
    private String  entryId;
    private String  triggerName;
    private String  triggerGroup;
    private String  instanceName;
    private Long    firedTime;
    private Long    schedTime;
    private Integer priority;
    private String  state;
    private String  jobName;
    private String  jobGroup;
    private Boolean isNonconcurrent;
    private Boolean requestsRecovery;

    public QrtzFiredTriggers() {}

    public QrtzFiredTriggers(QrtzFiredTriggers value) {
        this.schedName = value.schedName;
        this.entryId = value.entryId;
        this.triggerName = value.triggerName;
        this.triggerGroup = value.triggerGroup;
        this.instanceName = value.instanceName;
        this.firedTime = value.firedTime;
        this.schedTime = value.schedTime;
        this.priority = value.priority;
        this.state = value.state;
        this.jobName = value.jobName;
        this.jobGroup = value.jobGroup;
        this.isNonconcurrent = value.isNonconcurrent;
        this.requestsRecovery = value.requestsRecovery;
    }

    public QrtzFiredTriggers(
        String  schedName,
        String  entryId,
        String  triggerName,
        String  triggerGroup,
        String  instanceName,
        Long    firedTime,
        Long    schedTime,
        Integer priority,
        String  state,
        String  jobName,
        String  jobGroup,
        Boolean isNonconcurrent,
        Boolean requestsRecovery
    ) {
        this.schedName = schedName;
        this.entryId = entryId;
        this.triggerName = triggerName;
        this.triggerGroup = triggerGroup;
        this.instanceName = instanceName;
        this.firedTime = firedTime;
        this.schedTime = schedTime;
        this.priority = priority;
        this.state = state;
        this.jobName = jobName;
        this.jobGroup = jobGroup;
        this.isNonconcurrent = isNonconcurrent;
        this.requestsRecovery = requestsRecovery;
    }

    public String getSchedName() {
        return this.schedName;
    }

    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    public String getEntryId() {
        return this.entryId;
    }

    public void setEntryId(String entryId) {
        this.entryId = entryId;
    }

    public String getTriggerName() {
        return this.triggerName;
    }

    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    public String getTriggerGroup() {
        return this.triggerGroup;
    }

    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    public String getInstanceName() {
        return this.instanceName;
    }

    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    public Long getFiredTime() {
        return this.firedTime;
    }

    public void setFiredTime(Long firedTime) {
        this.firedTime = firedTime;
    }

    public Long getSchedTime() {
        return this.schedTime;
    }

    public void setSchedTime(Long schedTime) {
        this.schedTime = schedTime;
    }

    public Integer getPriority() {
        return this.priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getJobName() {
        return this.jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public String getJobGroup() {
        return this.jobGroup;
    }

    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    public Boolean getIsNonconcurrent() {
        return this.isNonconcurrent;
    }

    public void setIsNonconcurrent(Boolean isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent;
    }

    public Boolean getRequestsRecovery() {
        return this.requestsRecovery;
    }

    public void setRequestsRecovery(Boolean requestsRecovery) {
        this.requestsRecovery = requestsRecovery;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QrtzFiredTriggers (");

        sb.append(schedName);
        sb.append(", ").append(entryId);
        sb.append(", ").append(triggerName);
        sb.append(", ").append(triggerGroup);
        sb.append(", ").append(instanceName);
        sb.append(", ").append(firedTime);
        sb.append(", ").append(schedTime);
        sb.append(", ").append(priority);
        sb.append(", ").append(state);
        sb.append(", ").append(jobName);
        sb.append(", ").append(jobGroup);
        sb.append(", ").append(isNonconcurrent);
        sb.append(", ").append(requestsRecovery);

        sb.append(")");
        return sb.toString();
    }
}
