/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.quartz.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzLocks implements Serializable {

    private static final long serialVersionUID = 1162120788;

    private String schedName;
    private String lockName;

    public QrtzLocks() {}

    public QrtzLocks(QrtzLocks value) {
        this.schedName = value.schedName;
        this.lockName = value.lockName;
    }

    public QrtzLocks(
        String schedName,
        String lockName
    ) {
        this.schedName = schedName;
        this.lockName = lockName;
    }

    public String getSchedName() {
        return this.schedName;
    }

    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    public String getLockName() {
        return this.lockName;
    }

    public void setLockName(String lockName) {
        this.lockName = lockName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QrtzLocks (");

        sb.append(schedName);
        sb.append(", ").append(lockName);

        sb.append(")");
        return sb.toString();
    }
}
