/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.quartz.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzTriggers implements Serializable {

    private static final long serialVersionUID = 1639581497;

    private String  schedName;
    private String  triggerName;
    private String  triggerGroup;
    private String  jobName;
    private String  jobGroup;
    private String  description;
    private Long    nextFireTime;
    private Long    prevFireTime;
    private Integer priority;
    private String  triggerState;
    private String  triggerType;
    private Long    startTime;
    private Long    endTime;
    private String  calendarName;
    private Short   misfireInstr;
    private byte[]  jobData;

    public QrtzTriggers() {}

    public QrtzTriggers(QrtzTriggers value) {
        this.schedName = value.schedName;
        this.triggerName = value.triggerName;
        this.triggerGroup = value.triggerGroup;
        this.jobName = value.jobName;
        this.jobGroup = value.jobGroup;
        this.description = value.description;
        this.nextFireTime = value.nextFireTime;
        this.prevFireTime = value.prevFireTime;
        this.priority = value.priority;
        this.triggerState = value.triggerState;
        this.triggerType = value.triggerType;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.calendarName = value.calendarName;
        this.misfireInstr = value.misfireInstr;
        this.jobData = value.jobData;
    }

    public QrtzTriggers(
        String  schedName,
        String  triggerName,
        String  triggerGroup,
        String  jobName,
        String  jobGroup,
        String  description,
        Long    nextFireTime,
        Long    prevFireTime,
        Integer priority,
        String  triggerState,
        String  triggerType,
        Long    startTime,
        Long    endTime,
        String  calendarName,
        Short   misfireInstr,
        byte[]  jobData
    ) {
        this.schedName = schedName;
        this.triggerName = triggerName;
        this.triggerGroup = triggerGroup;
        this.jobName = jobName;
        this.jobGroup = jobGroup;
        this.description = description;
        this.nextFireTime = nextFireTime;
        this.prevFireTime = prevFireTime;
        this.priority = priority;
        this.triggerState = triggerState;
        this.triggerType = triggerType;
        this.startTime = startTime;
        this.endTime = endTime;
        this.calendarName = calendarName;
        this.misfireInstr = misfireInstr;
        this.jobData = jobData;
    }

    public String getSchedName() {
        return this.schedName;
    }

    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    public String getTriggerName() {
        return this.triggerName;
    }

    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    public String getTriggerGroup() {
        return this.triggerGroup;
    }

    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    public String getJobName() {
        return this.jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public String getJobGroup() {
        return this.jobGroup;
    }

    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getNextFireTime() {
        return this.nextFireTime;
    }

    public void setNextFireTime(Long nextFireTime) {
        this.nextFireTime = nextFireTime;
    }

    public Long getPrevFireTime() {
        return this.prevFireTime;
    }

    public void setPrevFireTime(Long prevFireTime) {
        this.prevFireTime = prevFireTime;
    }

    public Integer getPriority() {
        return this.priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public String getTriggerState() {
        return this.triggerState;
    }

    public void setTriggerState(String triggerState) {
        this.triggerState = triggerState;
    }

    public String getTriggerType() {
        return this.triggerType;
    }

    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType;
    }

    public Long getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public String getCalendarName() {
        return this.calendarName;
    }

    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName;
    }

    public Short getMisfireInstr() {
        return this.misfireInstr;
    }

    public void setMisfireInstr(Short misfireInstr) {
        this.misfireInstr = misfireInstr;
    }

    public byte[] getJobData() {
        return this.jobData;
    }

    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QrtzTriggers (");

        sb.append(schedName);
        sb.append(", ").append(triggerName);
        sb.append(", ").append(triggerGroup);
        sb.append(", ").append(jobName);
        sb.append(", ").append(jobGroup);
        sb.append(", ").append(description);
        sb.append(", ").append(nextFireTime);
        sb.append(", ").append(prevFireTime);
        sb.append(", ").append(priority);
        sb.append(", ").append(triggerState);
        sb.append(", ").append(triggerType);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(calendarName);
        sb.append(", ").append(misfireInstr);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
