/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgHbaFileRules implements Serializable {

    private static final long serialVersionUID = -242529523;

    private Integer  lineNumber;
    private String   type;
    private String[] database;
    private String[] userName;
    private String   address;
    private String   netmask;
    private String   authMethod;
    private String[] options;
    private String   error;

    public PgHbaFileRules() {}

    public PgHbaFileRules(PgHbaFileRules value) {
        this.lineNumber = value.lineNumber;
        this.type = value.type;
        this.database = value.database;
        this.userName = value.userName;
        this.address = value.address;
        this.netmask = value.netmask;
        this.authMethod = value.authMethod;
        this.options = value.options;
        this.error = value.error;
    }

    public PgHbaFileRules(
        Integer  lineNumber,
        String   type,
        String[] database,
        String[] userName,
        String   address,
        String   netmask,
        String   authMethod,
        String[] options,
        String   error
    ) {
        this.lineNumber = lineNumber;
        this.type = type;
        this.database = database;
        this.userName = userName;
        this.address = address;
        this.netmask = netmask;
        this.authMethod = authMethod;
        this.options = options;
        this.error = error;
    }

    public Integer getLineNumber() {
        return this.lineNumber;
    }

    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String[] getDatabase() {
        return this.database;
    }

    public void setDatabase(String[] database) {
        this.database = database;
    }

    public String[] getUserName() {
        return this.userName;
    }

    public void setUserName(String[] userName) {
        this.userName = userName;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getNetmask() {
        return this.netmask;
    }

    public void setNetmask(String netmask) {
        this.netmask = netmask;
    }

    public String getAuthMethod() {
        return this.authMethod;
    }

    public void setAuthMethod(String authMethod) {
        this.authMethod = authMethod;
    }

    public String[] getOptions() {
        return this.options;
    }

    public void setOptions(String[] options) {
        this.options = options;
    }

    public String getError() {
        return this.error;
    }

    public void setError(String error) {
        this.error = error;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgHbaFileRules (");

        sb.append(lineNumber);
        sb.append(", ").append(type);
        sb.append(", ").append(Arrays.toString(database));
        sb.append(", ").append(Arrays.toString(userName));
        sb.append(", ").append(address);
        sb.append(", ").append(netmask);
        sb.append(", ").append(authMethod);
        sb.append(", ").append(Arrays.toString(options));
        sb.append(", ").append(error);

        sb.append(")");
        return sb.toString();
    }
}
