/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgLargeobject implements Serializable {

    private static final long serialVersionUID = 2092360507;

    private Long    loid;
    private Integer pageno;
    private byte[]  data;

    public PgLargeobject() {}

    public PgLargeobject(PgLargeobject value) {
        this.loid = value.loid;
        this.pageno = value.pageno;
        this.data = value.data;
    }

    public PgLargeobject(
        Long    loid,
        Integer pageno,
        byte[]  data
    ) {
        this.loid = loid;
        this.pageno = pageno;
        this.data = data;
    }

    public Long getLoid() {
        return this.loid;
    }

    public void setLoid(Long loid) {
        this.loid = loid;
    }

    public Integer getPageno() {
        return this.pageno;
    }

    public void setPageno(Integer pageno) {
        this.pageno = pageno;
    }

    public byte[] getData() {
        return this.data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgLargeobject (");

        sb.append(loid);
        sb.append(", ").append(pageno);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
