/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPublication implements Serializable {

    private static final long serialVersionUID = -2123149842;

    private String  pubname;
    private Long    pubowner;
    private Boolean puballtables;
    private Boolean pubinsert;
    private Boolean pubupdate;
    private Boolean pubdelete;
    private Boolean pubtruncate;

    public PgPublication() {}

    public PgPublication(PgPublication value) {
        this.pubname = value.pubname;
        this.pubowner = value.pubowner;
        this.puballtables = value.puballtables;
        this.pubinsert = value.pubinsert;
        this.pubupdate = value.pubupdate;
        this.pubdelete = value.pubdelete;
        this.pubtruncate = value.pubtruncate;
    }

    public PgPublication(
        String  pubname,
        Long    pubowner,
        Boolean puballtables,
        Boolean pubinsert,
        Boolean pubupdate,
        Boolean pubdelete,
        Boolean pubtruncate
    ) {
        this.pubname = pubname;
        this.pubowner = pubowner;
        this.puballtables = puballtables;
        this.pubinsert = pubinsert;
        this.pubupdate = pubupdate;
        this.pubdelete = pubdelete;
        this.pubtruncate = pubtruncate;
    }

    public String getPubname() {
        return this.pubname;
    }

    public void setPubname(String pubname) {
        this.pubname = pubname;
    }

    public Long getPubowner() {
        return this.pubowner;
    }

    public void setPubowner(Long pubowner) {
        this.pubowner = pubowner;
    }

    public Boolean getPuballtables() {
        return this.puballtables;
    }

    public void setPuballtables(Boolean puballtables) {
        this.puballtables = puballtables;
    }

    public Boolean getPubinsert() {
        return this.pubinsert;
    }

    public void setPubinsert(Boolean pubinsert) {
        this.pubinsert = pubinsert;
    }

    public Boolean getPubupdate() {
        return this.pubupdate;
    }

    public void setPubupdate(Boolean pubupdate) {
        this.pubupdate = pubupdate;
    }

    public Boolean getPubdelete() {
        return this.pubdelete;
    }

    public void setPubdelete(Boolean pubdelete) {
        this.pubdelete = pubdelete;
    }

    public Boolean getPubtruncate() {
        return this.pubtruncate;
    }

    public void setPubtruncate(Boolean pubtruncate) {
        this.pubtruncate = pubtruncate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgPublication (");

        sb.append(pubname);
        sb.append(", ").append(pubowner);
        sb.append(", ").append(puballtables);
        sb.append(", ").append(pubinsert);
        sb.append(", ").append(pubupdate);
        sb.append(", ").append(pubdelete);
        sb.append(", ").append(pubtruncate);

        sb.append(")");
        return sb.toString();
    }
}
