/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatArchiver implements Serializable {

    private static final long serialVersionUID = 2097279265;

    private Long      archivedCount;
    private String    lastArchivedWal;
    private Timestamp lastArchivedTime;
    private Long      failedCount;
    private String    lastFailedWal;
    private Timestamp lastFailedTime;
    private Timestamp statsReset;

    public PgStatArchiver() {}

    public PgStatArchiver(PgStatArchiver value) {
        this.archivedCount = value.archivedCount;
        this.lastArchivedWal = value.lastArchivedWal;
        this.lastArchivedTime = value.lastArchivedTime;
        this.failedCount = value.failedCount;
        this.lastFailedWal = value.lastFailedWal;
        this.lastFailedTime = value.lastFailedTime;
        this.statsReset = value.statsReset;
    }

    public PgStatArchiver(
        Long      archivedCount,
        String    lastArchivedWal,
        Timestamp lastArchivedTime,
        Long      failedCount,
        String    lastFailedWal,
        Timestamp lastFailedTime,
        Timestamp statsReset
    ) {
        this.archivedCount = archivedCount;
        this.lastArchivedWal = lastArchivedWal;
        this.lastArchivedTime = lastArchivedTime;
        this.failedCount = failedCount;
        this.lastFailedWal = lastFailedWal;
        this.lastFailedTime = lastFailedTime;
        this.statsReset = statsReset;
    }

    public Long getArchivedCount() {
        return this.archivedCount;
    }

    public void setArchivedCount(Long archivedCount) {
        this.archivedCount = archivedCount;
    }

    public String getLastArchivedWal() {
        return this.lastArchivedWal;
    }

    public void setLastArchivedWal(String lastArchivedWal) {
        this.lastArchivedWal = lastArchivedWal;
    }

    public Timestamp getLastArchivedTime() {
        return this.lastArchivedTime;
    }

    public void setLastArchivedTime(Timestamp lastArchivedTime) {
        this.lastArchivedTime = lastArchivedTime;
    }

    public Long getFailedCount() {
        return this.failedCount;
    }

    public void setFailedCount(Long failedCount) {
        this.failedCount = failedCount;
    }

    public String getLastFailedWal() {
        return this.lastFailedWal;
    }

    public void setLastFailedWal(String lastFailedWal) {
        this.lastFailedWal = lastFailedWal;
    }

    public Timestamp getLastFailedTime() {
        return this.lastFailedTime;
    }

    public void setLastFailedTime(Timestamp lastFailedTime) {
        this.lastFailedTime = lastFailedTime;
    }

    public Timestamp getStatsReset() {
        return this.statsReset;
    }

    public void setStatsReset(Timestamp statsReset) {
        this.statsReset = statsReset;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatArchiver (");

        sb.append(archivedCount);
        sb.append(", ").append(lastArchivedWal);
        sb.append(", ").append(lastArchivedTime);
        sb.append(", ").append(failedCount);
        sb.append(", ").append(lastFailedWal);
        sb.append(", ").append(lastFailedTime);
        sb.append(", ").append(statsReset);

        sb.append(")");
        return sb.toString();
    }
}
