/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatWalReceiver implements Serializable {

    private static final long serialVersionUID = 840734491;

    private Integer   pid;
    private String    status;
    private Object    receiveStartLsn;
    private Integer   receiveStartTli;
    private Object    receivedLsn;
    private Integer   receivedTli;
    private Timestamp lastMsgSendTime;
    private Timestamp lastMsgReceiptTime;
    private Object    latestEndLsn;
    private Timestamp latestEndTime;
    private String    slotName;
    private String    senderHost;
    private Integer   senderPort;
    private String    conninfo;

    public PgStatWalReceiver() {}

    public PgStatWalReceiver(PgStatWalReceiver value) {
        this.pid = value.pid;
        this.status = value.status;
        this.receiveStartLsn = value.receiveStartLsn;
        this.receiveStartTli = value.receiveStartTli;
        this.receivedLsn = value.receivedLsn;
        this.receivedTli = value.receivedTli;
        this.lastMsgSendTime = value.lastMsgSendTime;
        this.lastMsgReceiptTime = value.lastMsgReceiptTime;
        this.latestEndLsn = value.latestEndLsn;
        this.latestEndTime = value.latestEndTime;
        this.slotName = value.slotName;
        this.senderHost = value.senderHost;
        this.senderPort = value.senderPort;
        this.conninfo = value.conninfo;
    }

    public PgStatWalReceiver(
        Integer   pid,
        String    status,
        Object    receiveStartLsn,
        Integer   receiveStartTli,
        Object    receivedLsn,
        Integer   receivedTli,
        Timestamp lastMsgSendTime,
        Timestamp lastMsgReceiptTime,
        Object    latestEndLsn,
        Timestamp latestEndTime,
        String    slotName,
        String    senderHost,
        Integer   senderPort,
        String    conninfo
    ) {
        this.pid = pid;
        this.status = status;
        this.receiveStartLsn = receiveStartLsn;
        this.receiveStartTli = receiveStartTli;
        this.receivedLsn = receivedLsn;
        this.receivedTli = receivedTli;
        this.lastMsgSendTime = lastMsgSendTime;
        this.lastMsgReceiptTime = lastMsgReceiptTime;
        this.latestEndLsn = latestEndLsn;
        this.latestEndTime = latestEndTime;
        this.slotName = slotName;
        this.senderHost = senderHost;
        this.senderPort = senderPort;
        this.conninfo = conninfo;
    }

    public Integer getPid() {
        return this.pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Object getReceiveStartLsn() {
        return this.receiveStartLsn;
    }

    public void setReceiveStartLsn(Object receiveStartLsn) {
        this.receiveStartLsn = receiveStartLsn;
    }

    public Integer getReceiveStartTli() {
        return this.receiveStartTli;
    }

    public void setReceiveStartTli(Integer receiveStartTli) {
        this.receiveStartTli = receiveStartTli;
    }

    public Object getReceivedLsn() {
        return this.receivedLsn;
    }

    public void setReceivedLsn(Object receivedLsn) {
        this.receivedLsn = receivedLsn;
    }

    public Integer getReceivedTli() {
        return this.receivedTli;
    }

    public void setReceivedTli(Integer receivedTli) {
        this.receivedTli = receivedTli;
    }

    public Timestamp getLastMsgSendTime() {
        return this.lastMsgSendTime;
    }

    public void setLastMsgSendTime(Timestamp lastMsgSendTime) {
        this.lastMsgSendTime = lastMsgSendTime;
    }

    public Timestamp getLastMsgReceiptTime() {
        return this.lastMsgReceiptTime;
    }

    public void setLastMsgReceiptTime(Timestamp lastMsgReceiptTime) {
        this.lastMsgReceiptTime = lastMsgReceiptTime;
    }

    public Object getLatestEndLsn() {
        return this.latestEndLsn;
    }

    public void setLatestEndLsn(Object latestEndLsn) {
        this.latestEndLsn = latestEndLsn;
    }

    public Timestamp getLatestEndTime() {
        return this.latestEndTime;
    }

    public void setLatestEndTime(Timestamp latestEndTime) {
        this.latestEndTime = latestEndTime;
    }

    public String getSlotName() {
        return this.slotName;
    }

    public void setSlotName(String slotName) {
        this.slotName = slotName;
    }

    public String getSenderHost() {
        return this.senderHost;
    }

    public void setSenderHost(String senderHost) {
        this.senderHost = senderHost;
    }

    public Integer getSenderPort() {
        return this.senderPort;
    }

    public void setSenderPort(Integer senderPort) {
        this.senderPort = senderPort;
    }

    public String getConninfo() {
        return this.conninfo;
    }

    public void setConninfo(String conninfo) {
        this.conninfo = conninfo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatWalReceiver (");

        sb.append(pid);
        sb.append(", ").append(status);
        sb.append(", ").append(receiveStartLsn);
        sb.append(", ").append(receiveStartTli);
        sb.append(", ").append(receivedLsn);
        sb.append(", ").append(receivedTli);
        sb.append(", ").append(lastMsgSendTime);
        sb.append(", ").append(lastMsgReceiptTime);
        sb.append(", ").append(latestEndLsn);
        sb.append(", ").append(latestEndTime);
        sb.append(", ").append(slotName);
        sb.append(", ").append(senderHost);
        sb.append(", ").append(senderPort);
        sb.append(", ").append(conninfo);

        sb.append(")");
        return sb.toString();
    }
}
