/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgSubscription implements Serializable {

    private static final long serialVersionUID = -1401279057;

    private Long     subdbid;
    private String   subname;
    private Long     subowner;
    private Boolean  subenabled;
    private String   subconninfo;
    private String   subslotname;
    private String   subsynccommit;
    private String[] subpublications;

    public PgSubscription() {}

    public PgSubscription(PgSubscription value) {
        this.subdbid = value.subdbid;
        this.subname = value.subname;
        this.subowner = value.subowner;
        this.subenabled = value.subenabled;
        this.subconninfo = value.subconninfo;
        this.subslotname = value.subslotname;
        this.subsynccommit = value.subsynccommit;
        this.subpublications = value.subpublications;
    }

    public PgSubscription(
        Long     subdbid,
        String   subname,
        Long     subowner,
        Boolean  subenabled,
        String   subconninfo,
        String   subslotname,
        String   subsynccommit,
        String[] subpublications
    ) {
        this.subdbid = subdbid;
        this.subname = subname;
        this.subowner = subowner;
        this.subenabled = subenabled;
        this.subconninfo = subconninfo;
        this.subslotname = subslotname;
        this.subsynccommit = subsynccommit;
        this.subpublications = subpublications;
    }

    public Long getSubdbid() {
        return this.subdbid;
    }

    public void setSubdbid(Long subdbid) {
        this.subdbid = subdbid;
    }

    public String getSubname() {
        return this.subname;
    }

    public void setSubname(String subname) {
        this.subname = subname;
    }

    public Long getSubowner() {
        return this.subowner;
    }

    public void setSubowner(Long subowner) {
        this.subowner = subowner;
    }

    public Boolean getSubenabled() {
        return this.subenabled;
    }

    public void setSubenabled(Boolean subenabled) {
        this.subenabled = subenabled;
    }

    public String getSubconninfo() {
        return this.subconninfo;
    }

    public void setSubconninfo(String subconninfo) {
        this.subconninfo = subconninfo;
    }

    public String getSubslotname() {
        return this.subslotname;
    }

    public void setSubslotname(String subslotname) {
        this.subslotname = subslotname;
    }

    public String getSubsynccommit() {
        return this.subsynccommit;
    }

    public void setSubsynccommit(String subsynccommit) {
        this.subsynccommit = subsynccommit;
    }

    public String[] getSubpublications() {
        return this.subpublications;
    }

    public void setSubpublications(String[] subpublications) {
        this.subpublications = subpublications;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgSubscription (");

        sb.append(subdbid);
        sb.append(", ").append(subname);
        sb.append(", ").append(subowner);
        sb.append(", ").append(subenabled);
        sb.append(", ").append(subconninfo);
        sb.append(", ").append(subslotname);
        sb.append(", ").append(subsynccommit);
        sb.append(", ").append(Arrays.toString(subpublications));

        sb.append(")");
        return sb.toString();
    }
}
