/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgTimezoneAbbrevs implements Serializable {

    private static final long serialVersionUID = -19526888;

    private String  abbrev;
    private Object  utcOffset;
    private Boolean isDst;

    public PgTimezoneAbbrevs() {}

    public PgTimezoneAbbrevs(PgTimezoneAbbrevs value) {
        this.abbrev = value.abbrev;
        this.utcOffset = value.utcOffset;
        this.isDst = value.isDst;
    }

    public PgTimezoneAbbrevs(
        String  abbrev,
        Object  utcOffset,
        Boolean isDst
    ) {
        this.abbrev = abbrev;
        this.utcOffset = utcOffset;
        this.isDst = isDst;
    }

    public String getAbbrev() {
        return this.abbrev;
    }

    public void setAbbrev(String abbrev) {
        this.abbrev = abbrev;
    }

    public Object getUtcOffset() {
        return this.utcOffset;
    }

    public void setUtcOffset(Object utcOffset) {
        this.utcOffset = utcOffset;
    }

    public Boolean getIsDst() {
        return this.isDst;
    }

    public void setIsDst(Boolean isDst) {
        this.isDst = isDst;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgTimezoneAbbrevs (");

        sb.append(abbrev);
        sb.append(", ").append(utcOffset);
        sb.append(", ").append(isDst);

        sb.append(")");
        return sb.toString();
    }
}
