/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_;


import com.nayanzin.springbootjooq.db.DefaultCatalog;
import com.nayanzin.springbootjooq.db.public_.tables.ApplicationWaypoints;
import com.nayanzin.springbootjooq.db.public_.tables.Applications;
import com.nayanzin.springbootjooq.db.public_.tables.Bids;
import com.nayanzin.springbootjooq.db.public_.tables.BillingContacts;
import com.nayanzin.springbootjooq.db.public_.tables.BillingCounters;
import com.nayanzin.springbootjooq.db.public_.tables.Branches;
import com.nayanzin.springbootjooq.db.public_.tables.Brands;
import com.nayanzin.springbootjooq.db.public_.tables.Countries;
import com.nayanzin.springbootjooq.db.public_.tables.CountryRegion;
import com.nayanzin.springbootjooq.db.public_.tables.Currencies;
import com.nayanzin.springbootjooq.db.public_.tables.CurrencyExchange;
import com.nayanzin.springbootjooq.db.public_.tables.Deals;
import com.nayanzin.springbootjooq.db.public_.tables.Documents;
import com.nayanzin.springbootjooq.db.public_.tables.FieldFormats;
import com.nayanzin.springbootjooq.db.public_.tables.GoogleApi;
import com.nayanzin.springbootjooq.db.public_.tables.Ip2location;
import com.nayanzin.springbootjooq.db.public_.tables.Models;
import com.nayanzin.springbootjooq.db.public_.tables.Negotiations;
import com.nayanzin.springbootjooq.db.public_.tables.OrderVehicles;
import com.nayanzin.springbootjooq.db.public_.tables.OrderWaypoints;
import com.nayanzin.springbootjooq.db.public_.tables.Orders;
import com.nayanzin.springbootjooq.db.public_.tables.Organizations;
import com.nayanzin.springbootjooq.db.public_.tables.Permissions;
import com.nayanzin.springbootjooq.db.public_.tables.PublicSources;
import com.nayanzin.springbootjooq.db.public_.tables.Ratings;
import com.nayanzin.springbootjooq.db.public_.tables.Roles;
import com.nayanzin.springbootjooq.db.public_.tables.SchemaVersion;
import com.nayanzin.springbootjooq.db.public_.tables.ShippingStatus;
import com.nayanzin.springbootjooq.db.public_.tables.Tenders;
import com.nayanzin.springbootjooq.db.public_.tables.TrailerTypes;
import com.nayanzin.springbootjooq.db.public_.tables.Translations;
import com.nayanzin.springbootjooq.db.public_.tables.TrkAccounts;
import com.nayanzin.springbootjooq.db.public_.tables.TrkAssignments;
import com.nayanzin.springbootjooq.db.public_.tables.TrkSystems;
import com.nayanzin.springbootjooq.db.public_.tables.TrkTrackers;
import com.nayanzin.springbootjooq.db.public_.tables.UserDefSettings;
import com.nayanzin.springbootjooq.db.public_.tables.UserPermissions;
import com.nayanzin.springbootjooq.db.public_.tables.UserRoles;
import com.nayanzin.springbootjooq.db.public_.tables.UserSettings;
import com.nayanzin.springbootjooq.db.public_.tables.Users;
import com.nayanzin.springbootjooq.db.public_.tables.Vehicles;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1641343151;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.application_waypoints</code>.
     */
    public final ApplicationWaypoints APPLICATION_WAYPOINTS = com.nayanzin.springbootjooq.db.public_.tables.ApplicationWaypoints.APPLICATION_WAYPOINTS;

    /**
     * The table <code>public.applications</code>.
     */
    public final Applications APPLICATIONS = com.nayanzin.springbootjooq.db.public_.tables.Applications.APPLICATIONS;

    /**
     * The table <code>public.bids</code>.
     */
    public final Bids BIDS = com.nayanzin.springbootjooq.db.public_.tables.Bids.BIDS;

    /**
     * The table <code>public.billing_contacts</code>.
     */
    public final BillingContacts BILLING_CONTACTS = com.nayanzin.springbootjooq.db.public_.tables.BillingContacts.BILLING_CONTACTS;

    /**
     * The table <code>public.billing_counters</code>.
     */
    public final BillingCounters BILLING_COUNTERS = com.nayanzin.springbootjooq.db.public_.tables.BillingCounters.BILLING_COUNTERS;

    /**
     * The table <code>public.branches</code>.
     */
    public final Branches BRANCHES = com.nayanzin.springbootjooq.db.public_.tables.Branches.BRANCHES;

    /**
     * The table <code>public.brands</code>.
     */
    public final Brands BRANDS = com.nayanzin.springbootjooq.db.public_.tables.Brands.BRANDS;

    /**
     * The table <code>public.countries</code>.
     */
    public final Countries COUNTRIES = com.nayanzin.springbootjooq.db.public_.tables.Countries.COUNTRIES;

    /**
     * The table <code>public.country_region</code>.
     */
    public final CountryRegion COUNTRY_REGION = com.nayanzin.springbootjooq.db.public_.tables.CountryRegion.COUNTRY_REGION;

    /**
     * The table <code>public.currencies</code>.
     */
    public final Currencies CURRENCIES = com.nayanzin.springbootjooq.db.public_.tables.Currencies.CURRENCIES;

    /**
     * The table <code>public.currency_exchange</code>.
     */
    public final CurrencyExchange CURRENCY_EXCHANGE = com.nayanzin.springbootjooq.db.public_.tables.CurrencyExchange.CURRENCY_EXCHANGE;

    /**
     * The table <code>public.deals</code>.
     */
    public final Deals DEALS = com.nayanzin.springbootjooq.db.public_.tables.Deals.DEALS;

    /**
     * The table <code>public.documents</code>.
     */
    public final Documents DOCUMENTS = com.nayanzin.springbootjooq.db.public_.tables.Documents.DOCUMENTS;

    /**
     * The table <code>public.field_formats</code>.
     */
    public final FieldFormats FIELD_FORMATS = com.nayanzin.springbootjooq.db.public_.tables.FieldFormats.FIELD_FORMATS;

    /**
     * The table <code>public.google_api</code>.
     */
    public final GoogleApi GOOGLE_API = com.nayanzin.springbootjooq.db.public_.tables.GoogleApi.GOOGLE_API;

    /**
     * The table <code>public.ip2location</code>.
     */
    public final Ip2location IP2LOCATION = com.nayanzin.springbootjooq.db.public_.tables.Ip2location.IP2LOCATION;

    /**
     * The table <code>public.models</code>.
     */
    public final Models MODELS = com.nayanzin.springbootjooq.db.public_.tables.Models.MODELS;

    /**
     * The table <code>public.negotiations</code>.
     */
    public final Negotiations NEGOTIATIONS = com.nayanzin.springbootjooq.db.public_.tables.Negotiations.NEGOTIATIONS;

    /**
     * The table <code>public.order_vehicles</code>.
     */
    public final OrderVehicles ORDER_VEHICLES = com.nayanzin.springbootjooq.db.public_.tables.OrderVehicles.ORDER_VEHICLES;

    /**
     * The table <code>public.order_waypoints</code>.
     */
    public final OrderWaypoints ORDER_WAYPOINTS = com.nayanzin.springbootjooq.db.public_.tables.OrderWaypoints.ORDER_WAYPOINTS;

    /**
     * The table <code>public.orders</code>.
     */
    public final Orders ORDERS = com.nayanzin.springbootjooq.db.public_.tables.Orders.ORDERS;

    /**
     * The table <code>public.organizations</code>.
     */
    public final Organizations ORGANIZATIONS = com.nayanzin.springbootjooq.db.public_.tables.Organizations.ORGANIZATIONS;

    /**
     * The table <code>public.permissions</code>.
     */
    public final Permissions PERMISSIONS = com.nayanzin.springbootjooq.db.public_.tables.Permissions.PERMISSIONS;

    /**
     * The table <code>public.public_sources</code>.
     */
    public final PublicSources PUBLIC_SOURCES = com.nayanzin.springbootjooq.db.public_.tables.PublicSources.PUBLIC_SOURCES;

    /**
     * The table <code>public.ratings</code>.
     */
    public final Ratings RATINGS = com.nayanzin.springbootjooq.db.public_.tables.Ratings.RATINGS;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = com.nayanzin.springbootjooq.db.public_.tables.Roles.ROLES;

    /**
     * The table <code>public.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.nayanzin.springbootjooq.db.public_.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>public.shipping_status</code>.
     */
    public final ShippingStatus SHIPPING_STATUS = com.nayanzin.springbootjooq.db.public_.tables.ShippingStatus.SHIPPING_STATUS;

    /**
     * The table <code>public.tenders</code>.
     */
    public final Tenders TENDERS = com.nayanzin.springbootjooq.db.public_.tables.Tenders.TENDERS;

    /**
     * The table <code>public.trailer_types</code>.
     */
    public final TrailerTypes TRAILER_TYPES = com.nayanzin.springbootjooq.db.public_.tables.TrailerTypes.TRAILER_TYPES;

    /**
     * The table <code>public.translations</code>.
     */
    public final Translations TRANSLATIONS = com.nayanzin.springbootjooq.db.public_.tables.Translations.TRANSLATIONS;

    /**
     * The table <code>public.trk_accounts</code>.
     */
    public final TrkAccounts TRK_ACCOUNTS = com.nayanzin.springbootjooq.db.public_.tables.TrkAccounts.TRK_ACCOUNTS;

    /**
     * The table <code>public.trk_assignments</code>.
     */
    public final TrkAssignments TRK_ASSIGNMENTS = com.nayanzin.springbootjooq.db.public_.tables.TrkAssignments.TRK_ASSIGNMENTS;

    /**
     * The table <code>public.trk_systems</code>.
     */
    public final TrkSystems TRK_SYSTEMS = com.nayanzin.springbootjooq.db.public_.tables.TrkSystems.TRK_SYSTEMS;

    /**
     * The table <code>public.trk_trackers</code>.
     */
    public final TrkTrackers TRK_TRACKERS = com.nayanzin.springbootjooq.db.public_.tables.TrkTrackers.TRK_TRACKERS;

    /**
     * The table <code>public.user_def_settings</code>.
     */
    public final UserDefSettings USER_DEF_SETTINGS = com.nayanzin.springbootjooq.db.public_.tables.UserDefSettings.USER_DEF_SETTINGS;

    /**
     * The table <code>public.user_permissions</code>.
     */
    public final UserPermissions USER_PERMISSIONS = com.nayanzin.springbootjooq.db.public_.tables.UserPermissions.USER_PERMISSIONS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final UserRoles USER_ROLES = com.nayanzin.springbootjooq.db.public_.tables.UserRoles.USER_ROLES;

    /**
     * The table <code>public.user_settings</code>.
     */
    public final UserSettings USER_SETTINGS = com.nayanzin.springbootjooq.db.public_.tables.UserSettings.USER_SETTINGS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.nayanzin.springbootjooq.db.public_.tables.Users.USERS;

    /**
     * Уникальный индекс по регистрационному знаку
     */
    public final Vehicles VEHICLES = com.nayanzin.springbootjooq.db.public_.tables.Vehicles.VEHICLES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.APPLICATION_WAYPOINTS_ID_SEQ,
            Sequences.APPLICATIONS_ID_SEQ,
            Sequences.BIDS_ID_SEQ,
            Sequences.BILLING_CONTACTS_ID_SEQ,
            Sequences.BILLING_COUNTERS_ID_SEQ,
            Sequences.BRANCHES_ID_SEQ,
            Sequences.BRANDS_ID_SEQ,
            Sequences.CURRENCY_EXCHANGE_SEQ,
            Sequences.DEALS_SEQ,
            Sequences.DOCUMENTS_SEQ,
            Sequences.FIELD_FORMATS_ID_SEQ,
            Sequences.MODELS_ID_SEQ,
            Sequences.NEGOTIATIONS_ID_SEQ,
            Sequences.ODER_PAYMENTS_ID_SEQ,
            Sequences.ORDER_VEHICLES_ID_SEQ,
            Sequences.ORDER_WAYPOINTS_ID_SEQ,
            Sequences.ORDERS_ID_SEQ,
            Sequences.ORGANIZATION_TYPE_ID_SEQ,
            Sequences.ORGANIZATIONS_ID_SEQ,
            Sequences.PERMISSION_ID_SEQ,
            Sequences.PUBLIC_SOURCES_ID_SEQ,
            Sequences.RATING_ID_SEQ,
            Sequences.ROLES_ID_SEQ,
            Sequences.ROUTE_WAYPOINTS_ID_SEQ,
            Sequences.TENDERS_ID_SEQ,
            Sequences.TRAILER_TYPES_ID_SEQ,
            Sequences.TRANSLATIONS_ID_SEQ,
            Sequences.TRK_ACCOUNT_ID_SEQ,
            Sequences.TRK_ASSIGNMENT_ID_SEQ,
            Sequences.TRK_INFO_ID_SEQ,
            Sequences.TRK_LOCATION_ID_SEQ,
            Sequences.TRK_SYSTEM_ID_SEQ,
            Sequences.TRK_TRACKER_ID_SEQ,
            Sequences.USER_PERMISSION_ID_SEQ,
            Sequences.USER_ROLES_ID_SEQ,
            Sequences.USERS_ID_SEQ,
            Sequences.VEHICLE_STATUS_SEQ,
            Sequences.VEHICLES_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ApplicationWaypoints.APPLICATION_WAYPOINTS,
            Applications.APPLICATIONS,
            Bids.BIDS,
            BillingContacts.BILLING_CONTACTS,
            BillingCounters.BILLING_COUNTERS,
            Branches.BRANCHES,
            Brands.BRANDS,
            Countries.COUNTRIES,
            CountryRegion.COUNTRY_REGION,
            Currencies.CURRENCIES,
            CurrencyExchange.CURRENCY_EXCHANGE,
            Deals.DEALS,
            Documents.DOCUMENTS,
            FieldFormats.FIELD_FORMATS,
            GoogleApi.GOOGLE_API,
            Ip2location.IP2LOCATION,
            Models.MODELS,
            Negotiations.NEGOTIATIONS,
            OrderVehicles.ORDER_VEHICLES,
            OrderWaypoints.ORDER_WAYPOINTS,
            Orders.ORDERS,
            Organizations.ORGANIZATIONS,
            Permissions.PERMISSIONS,
            PublicSources.PUBLIC_SOURCES,
            Ratings.RATINGS,
            Roles.ROLES,
            SchemaVersion.SCHEMA_VERSION,
            ShippingStatus.SHIPPING_STATUS,
            Tenders.TENDERS,
            TrailerTypes.TRAILER_TYPES,
            Translations.TRANSLATIONS,
            TrkAccounts.TRK_ACCOUNTS,
            TrkAssignments.TRK_ASSIGNMENTS,
            TrkSystems.TRK_SYSTEMS,
            TrkTrackers.TRK_TRACKERS,
            UserDefSettings.USER_DEF_SETTINGS,
            UserPermissions.USER_PERMISSIONS,
            UserRoles.USER_ROLES,
            UserSettings.USER_SETTINGS,
            Users.USERS,
            Vehicles.VEHICLES);
    }
}
