/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.application_waypoints_id_seq</code>
     */
    public static final Sequence<Long> APPLICATION_WAYPOINTS_ID_SEQ = new SequenceImpl<Long>("application_waypoints_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.applications_id_seq</code>
     */
    public static final Sequence<Long> APPLICATIONS_ID_SEQ = new SequenceImpl<Long>("applications_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.bids_id_seq</code>
     */
    public static final Sequence<Long> BIDS_ID_SEQ = new SequenceImpl<Long>("bids_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.billing_contacts_id_seq</code>
     */
    public static final Sequence<Long> BILLING_CONTACTS_ID_SEQ = new SequenceImpl<Long>("billing_contacts_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.billing_counters_id_seq</code>
     */
    public static final Sequence<Long> BILLING_COUNTERS_ID_SEQ = new SequenceImpl<Long>("billing_counters_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.branches_id_seq</code>
     */
    public static final Sequence<Long> BRANCHES_ID_SEQ = new SequenceImpl<Long>("branches_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.brands_id_seq</code>
     */
    public static final Sequence<Long> BRANDS_ID_SEQ = new SequenceImpl<Long>("brands_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.currency_exchange_seq</code>
     */
    public static final Sequence<Long> CURRENCY_EXCHANGE_SEQ = new SequenceImpl<Long>("currency_exchange_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.deals_seq</code>
     */
    public static final Sequence<Long> DEALS_SEQ = new SequenceImpl<Long>("deals_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.documents_seq</code>
     */
    public static final Sequence<Long> DOCUMENTS_SEQ = new SequenceImpl<Long>("documents_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.field_formats_id_seq</code>
     */
    public static final Sequence<Long> FIELD_FORMATS_ID_SEQ = new SequenceImpl<Long>("field_formats_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.models_id_seq</code>
     */
    public static final Sequence<Long> MODELS_ID_SEQ = new SequenceImpl<Long>("models_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.negotiations_id_seq</code>
     */
    public static final Sequence<Long> NEGOTIATIONS_ID_SEQ = new SequenceImpl<Long>("negotiations_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.oder_payments_id_seq</code>
     */
    public static final Sequence<Long> ODER_PAYMENTS_ID_SEQ = new SequenceImpl<Long>("oder_payments_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.order_vehicles_id_seq</code>
     */
    public static final Sequence<Long> ORDER_VEHICLES_ID_SEQ = new SequenceImpl<Long>("order_vehicles_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.order_waypoints_id_seq</code>
     */
    public static final Sequence<Long> ORDER_WAYPOINTS_ID_SEQ = new SequenceImpl<Long>("order_waypoints_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.orders_id_seq</code>
     */
    public static final Sequence<Long> ORDERS_ID_SEQ = new SequenceImpl<Long>("orders_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.organization_type_id_seq</code>
     */
    public static final Sequence<Long> ORGANIZATION_TYPE_ID_SEQ = new SequenceImpl<Long>("organization_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.organizations_id_seq</code>
     */
    public static final Sequence<Long> ORGANIZATIONS_ID_SEQ = new SequenceImpl<Long>("organizations_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.permission_id_seq</code>
     */
    public static final Sequence<Long> PERMISSION_ID_SEQ = new SequenceImpl<Long>("permission_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.public_sources_id_seq</code>
     */
    public static final Sequence<Long> PUBLIC_SOURCES_ID_SEQ = new SequenceImpl<Long>("public_sources_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.rating_id_seq</code>
     */
    public static final Sequence<Long> RATING_ID_SEQ = new SequenceImpl<Long>("rating_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.roles_id_seq</code>
     */
    public static final Sequence<Long> ROLES_ID_SEQ = new SequenceImpl<Long>("roles_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.route_waypoints_id_seq</code>
     */
    public static final Sequence<Long> ROUTE_WAYPOINTS_ID_SEQ = new SequenceImpl<Long>("route_waypoints_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tenders_id_seq</code>
     */
    public static final Sequence<Long> TENDERS_ID_SEQ = new SequenceImpl<Long>("tenders_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.trailer_types_id_seq</code>
     */
    public static final Sequence<Long> TRAILER_TYPES_ID_SEQ = new SequenceImpl<Long>("trailer_types_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.translations_id_seq</code>
     */
    public static final Sequence<Long> TRANSLATIONS_ID_SEQ = new SequenceImpl<Long>("translations_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.trk_account_id_seq</code>
     */
    public static final Sequence<Long> TRK_ACCOUNT_ID_SEQ = new SequenceImpl<Long>("trk_account_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.trk_assignment_id_seq</code>
     */
    public static final Sequence<Long> TRK_ASSIGNMENT_ID_SEQ = new SequenceImpl<Long>("trk_assignment_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.trk_info_id_seq</code>
     */
    public static final Sequence<Long> TRK_INFO_ID_SEQ = new SequenceImpl<Long>("trk_info_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.trk_location_id_seq</code>
     */
    public static final Sequence<Long> TRK_LOCATION_ID_SEQ = new SequenceImpl<Long>("trk_location_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.trk_system_id_seq</code>
     */
    public static final Sequence<Long> TRK_SYSTEM_ID_SEQ = new SequenceImpl<Long>("trk_system_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.trk_tracker_id_seq</code>
     */
    public static final Sequence<Long> TRK_TRACKER_ID_SEQ = new SequenceImpl<Long>("trk_tracker_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_permission_id_seq</code>
     */
    public static final Sequence<Long> USER_PERMISSION_ID_SEQ = new SequenceImpl<Long>("user_permission_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_roles_id_seq</code>
     */
    public static final Sequence<Long> USER_ROLES_ID_SEQ = new SequenceImpl<Long>("user_roles_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.users_id_seq</code>
     */
    public static final Sequence<Long> USERS_ID_SEQ = new SequenceImpl<Long>("users_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.vehicle_status_seq</code>
     */
    public static final Sequence<Long> VEHICLE_STATUS_SEQ = new SequenceImpl<Long>("vehicle_status_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.vehicles_id_seq</code>
     */
    public static final Sequence<Long> VEHICLES_ID_SEQ = new SequenceImpl<Long>("vehicles_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
