/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.records;


import com.nayanzin.springbootjooq.db.public_.tables.FieldFormats;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FieldFormatsRecord extends UpdatableRecordImpl<FieldFormatsRecord> implements Record8<Integer, String, String, String, Timestamp, Timestamp, String, String> {

    private static final long serialVersionUID = -2017344187;

    /**
     * Setter for <code>public.field_formats.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.field_formats.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.field_formats.field_code</code>.
     */
    public void setFieldCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.field_formats.field_code</code>.
     */
    public String getFieldCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.field_formats.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.field_formats.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.field_formats.format</code>.
     */
    public void setFormat(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.field_formats.format</code>.
     */
    public String getFormat() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.field_formats.created_date</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.field_formats.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.field_formats.modified_date</code>.
     */
    public void setModifiedDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.field_formats.modified_date</code>.
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.field_formats.created_user</code>.
     */
    public void setCreatedUser(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.field_formats.created_user</code>.
     */
    public String getCreatedUser() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.field_formats.modified_user</code>.
     */
    public void setModifiedUser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.field_formats.modified_user</code>.
     */
    public String getModifiedUser() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Timestamp, Timestamp, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FieldFormats.FIELD_FORMATS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FieldFormats.FIELD_FORMATS.FIELD_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FieldFormats.FIELD_FORMATS.COUNTRY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return FieldFormats.FIELD_FORMATS.FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return FieldFormats.FIELD_FORMATS.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return FieldFormats.FIELD_FORMATS.MODIFIED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FieldFormats.FIELD_FORMATS.CREATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return FieldFormats.FIELD_FORMATS.MODIFIED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFieldCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getModifiedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord value2(String value) {
        setFieldCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord value3(String value) {
        setCountryCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord value4(String value) {
        setFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord value5(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord value6(Timestamp value) {
        setModifiedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord value7(String value) {
        setCreatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord value8(String value) {
        setModifiedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldFormatsRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FieldFormatsRecord
     */
    public FieldFormatsRecord() {
        super(FieldFormats.FIELD_FORMATS);
    }

    /**
     * Create a detached, initialised FieldFormatsRecord
     */
    public FieldFormatsRecord(Integer id, String fieldCode, String countryCode, String format, Timestamp createdDate, Timestamp modifiedDate, String createdUser, String modifiedUser) {
        super(FieldFormats.FIELD_FORMATS);

        set(0, id);
        set(1, fieldCode);
        set(2, countryCode);
        set(3, format);
        set(4, createdDate);
        set(5, modifiedDate);
        set(6, createdUser);
        set(7, modifiedUser);
    }
}
