/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.records;


import com.nayanzin.springbootjooq.db.public_.tables.OrderVehicles;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderVehiclesRecord extends UpdatableRecordImpl<OrderVehiclesRecord> implements Record4<Long, Long, Long, Short> {

    private static final long serialVersionUID = 168000288;

    /**
     * Setter for <code>public.order_vehicles.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_vehicles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.order_vehicles.order_id</code>.
     */
    public void setOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_vehicles.order_id</code>.
     */
    public Long getOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.order_vehicles.vehicle_id</code>.
     */
    public void setVehicleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_vehicles.vehicle_id</code>.
     */
    public Long getVehicleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.order_vehicles.vehicle_type</code>.
     */
    public void setVehicleType(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order_vehicles.vehicle_type</code>.
     */
    public Short getVehicleType() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OrderVehicles.ORDER_VEHICLES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return OrderVehicles.ORDER_VEHICLES.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return OrderVehicles.ORDER_VEHICLES.VEHICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return OrderVehicles.ORDER_VEHICLES.VEHICLE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getVehicleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getVehicleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderVehiclesRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderVehiclesRecord value2(Long value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderVehiclesRecord value3(Long value) {
        setVehicleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderVehiclesRecord value4(Short value) {
        setVehicleType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderVehiclesRecord values(Long value1, Long value2, Long value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderVehiclesRecord
     */
    public OrderVehiclesRecord() {
        super(OrderVehicles.ORDER_VEHICLES);
    }

    /**
     * Create a detached, initialised OrderVehiclesRecord
     */
    public OrderVehiclesRecord(Long id, Long orderId, Long vehicleId, Short vehicleType) {
        super(OrderVehicles.ORDER_VEHICLES);

        set(0, id);
        set(1, orderId);
        set(2, vehicleId);
        set(3, vehicleType);
    }
}
