/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.records;


import com.nayanzin.springbootjooq.db.public_.tables.Ratings;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingsRecord extends UpdatableRecordImpl<RatingsRecord> implements Record10<Long, Long, Long, Short, String, Boolean, Boolean, Timestamp, Long, Long> {

    private static final long serialVersionUID = -1423654001;

    /**
     * Setter for <code>public.ratings.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ratings.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ratings.rated_org_id</code>.
     */
    public void setRatedOrgId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ratings.rated_org_id</code>.
     */
    public Long getRatedOrgId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.ratings.rater_org_id</code>.
     */
    public void setRaterOrgId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ratings.rater_org_id</code>.
     */
    public Long getRaterOrgId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.ratings.mark</code>.
     */
    public void setMark(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ratings.mark</code>.
     */
    public Short getMark() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.ratings.comment</code>.
     */
    public void setComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ratings.comment</code>.
     */
    public String getComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.ratings.anonymous</code>.
     */
    public void setAnonymous(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ratings.anonymous</code>.
     */
    public Boolean getAnonymous() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.ratings.show_cargo</code>.
     */
    public void setShowCargo(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ratings.show_cargo</code>.
     */
    public Boolean getShowCargo() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.ratings.created_date</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ratings.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.ratings.deal_id</code>.
     */
    public void setDealId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.ratings.deal_id</code>.
     */
    public Long getDealId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.ratings.created_user</code>.
     */
    public void setCreatedUser(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.ratings.created_user</code>.
     */
    public Long getCreatedUser() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, Short, String, Boolean, Boolean, Timestamp, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, Short, String, Boolean, Boolean, Timestamp, Long, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Ratings.RATINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Ratings.RATINGS.RATED_ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Ratings.RATINGS.RATER_ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return Ratings.RATINGS.MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Ratings.RATINGS.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Ratings.RATINGS.ANONYMOUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Ratings.RATINGS.SHOW_CARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Ratings.RATINGS.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Ratings.RATINGS.DEAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Ratings.RATINGS.CREATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRatedOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getRaterOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getAnonymous();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getShowCargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getDealId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value2(Long value) {
        setRatedOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value3(Long value) {
        setRaterOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value4(Short value) {
        setMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value5(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value6(Boolean value) {
        setAnonymous(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value7(Boolean value) {
        setShowCargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value8(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value9(Long value) {
        setDealId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord value10(Long value) {
        setCreatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RatingsRecord values(Long value1, Long value2, Long value3, Short value4, String value5, Boolean value6, Boolean value7, Timestamp value8, Long value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RatingsRecord
     */
    public RatingsRecord() {
        super(Ratings.RATINGS);
    }

    /**
     * Create a detached, initialised RatingsRecord
     */
    public RatingsRecord(Long id, Long ratedOrgId, Long raterOrgId, Short mark, String comment, Boolean anonymous, Boolean showCargo, Timestamp createdDate, Long dealId, Long createdUser) {
        super(Ratings.RATINGS);

        set(0, id);
        set(1, ratedOrgId);
        set(2, raterOrgId);
        set(3, mark);
        set(4, comment);
        set(5, anonymous);
        set(6, showCargo);
        set(7, createdDate);
        set(8, dealId);
        set(9, createdUser);
    }
}
