/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.records;


import com.nayanzin.springbootjooq.db.public_.tables.TrkTrackers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrkTrackersRecord extends UpdatableRecordImpl<TrkTrackersRecord> implements Record6<Long, String, String, Integer, Integer, Long> {

    private static final long serialVersionUID = 1138602421;

    /**
     * Setter for <code>public.trk_trackers.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trk_trackers.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.trk_trackers.device_id</code>.
     */
    public void setDeviceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trk_trackers.device_id</code>.
     */
    public String getDeviceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trk_trackers.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trk_trackers.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.trk_trackers.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.trk_trackers.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.trk_trackers.system_id</code>.
     */
    public void setSystemId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.trk_trackers.system_id</code>.
     */
    public Integer getSystemId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.trk_trackers.vehicle_id</code>.
     */
    public void setVehicleId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.trk_trackers.vehicle_id</code>.
     */
    public Long getVehicleId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, Integer, Integer, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, Integer, Integer, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TrkTrackers.TRK_TRACKERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TrkTrackers.TRK_TRACKERS.DEVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TrkTrackers.TRK_TRACKERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TrkTrackers.TRK_TRACKERS.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TrkTrackers.TRK_TRACKERS.SYSTEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return TrkTrackers.TRK_TRACKERS.VEHICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getVehicleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrkTrackersRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrkTrackersRecord value2(String value) {
        setDeviceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrkTrackersRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrkTrackersRecord value4(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrkTrackersRecord value5(Integer value) {
        setSystemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrkTrackersRecord value6(Long value) {
        setVehicleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrkTrackersRecord values(Long value1, String value2, String value3, Integer value4, Integer value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrkTrackersRecord
     */
    public TrkTrackersRecord() {
        super(TrkTrackers.TRK_TRACKERS);
    }

    /**
     * Create a detached, initialised TrkTrackersRecord
     */
    public TrkTrackersRecord(Long id, String deviceId, String name, Integer accountId, Integer systemId, Long vehicleId) {
        super(TrkTrackers.TRK_TRACKERS);

        set(0, id);
        set(1, deviceId);
        set(2, name);
        set(3, accountId);
        set(4, systemId);
        set(5, vehicleId);
    }
}
