/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.records;


import com.nayanzin.springbootjooq.db.public_.tables.UserSettings;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettingsRecord extends UpdatableRecordImpl<UserSettingsRecord> implements Record6<Long, Object, Timestamp, Timestamp, Long, Long> {

    private static final long serialVersionUID = 514603373;

    /**
     * Setter for <code>public.user_settings.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_settings.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_settings.data</code>.
     */
    public void setData(Object value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_settings.data</code>.
     */
    public Object getData() {
        return (Object) get(1);
    }

    /**
     * Setter for <code>public.user_settings.created_date</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_settings.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.user_settings.modified_date</code>.
     */
    public void setModifiedDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_settings.modified_date</code>.
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.user_settings.created_user</code>.
     */
    public void setCreatedUser(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_settings.created_user</code>.
     */
    public Long getCreatedUser() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.user_settings.modified_user</code>.
     */
    public void setModifiedUser(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_settings.modified_user</code>.
     */
    public Long getModifiedUser() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Object, Timestamp, Timestamp, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Object, Timestamp, Timestamp, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserSettings.USER_SETTINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field2() {
        return UserSettings.USER_SETTINGS.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return UserSettings.USER_SETTINGS.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return UserSettings.USER_SETTINGS.MODIFIED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return UserSettings.USER_SETTINGS.CREATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return UserSettings.USER_SETTINGS.MODIFIED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value2() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getModifiedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value2(Object value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value3(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value4(Timestamp value) {
        setModifiedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value5(Long value) {
        setCreatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord value6(Long value) {
        setModifiedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingsRecord values(Long value1, Object value2, Timestamp value3, Timestamp value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSettingsRecord
     */
    public UserSettingsRecord() {
        super(UserSettings.USER_SETTINGS);
    }

    /**
     * Create a detached, initialised UserSettingsRecord
     */
    public UserSettingsRecord(Long id, Object data, Timestamp createdDate, Timestamp modifiedDate, Long createdUser, Long modifiedUser) {
        super(UserSettings.USER_SETTINGS);

        set(0, id);
        set(1, data);
        set(2, createdDate);
        set(3, modifiedDate);
        set(4, createdUser);
        set(5, modifiedUser);
    }
}
