/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.records;


import com.nayanzin.springbootjooq.db.public_.enums.VehStatus;
import com.nayanzin.springbootjooq.db.public_.tables.Vehicles;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Уникальный индекс по регистрационному знаку
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehiclesRecord extends UpdatableRecordImpl<VehiclesRecord> implements Record18<Long, Long, Long, String, Integer, Timestamp, Timestamp, String, String, BigDecimal, Integer, BigDecimal, Integer, Integer, String, Long, VehStatus, Long> {

    private static final long serialVersionUID = 1819652154;

    /**
     * Setter for <code>public.vehicles.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vehicles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vehicles.model_id</code>.
     */
    public void setModelId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vehicles.model_id</code>.
     */
    public Long getModelId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.vehicles.branch_id</code>.
     */
    public void setBranchId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vehicles.branch_id</code>.
     */
    public Long getBranchId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.vehicles.reg</code>.
     */
    public void setReg(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vehicles.reg</code>.
     */
    public String getReg() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.vehicles.trailer_id</code>.
     */
    public void setTrailerId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vehicles.trailer_id</code>.
     */
    public Integer getTrailerId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.vehicles.created_date</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vehicles.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.vehicles.modified_date</code>.
     */
    public void setModifiedDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vehicles.modified_date</code>.
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.vehicles.modified_user</code>.
     */
    public void setModifiedUser(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.vehicles.modified_user</code>.
     */
    public String getModifiedUser() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.vehicles.shipping_status_code</code>.
     */
    public void setShippingStatusCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.vehicles.shipping_status_code</code>.
     */
    public String getShippingStatusCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.vehicles.capacity</code>.
     */
    public void setCapacity(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.vehicles.capacity</code>.
     */
    public BigDecimal getCapacity() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.vehicles.capacity_unit</code>.
     */
    public void setCapacityUnit(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.vehicles.capacity_unit</code>.
     */
    public Integer getCapacityUnit() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.vehicles.volume</code>.
     */
    public void setVolume(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.vehicles.volume</code>.
     */
    public BigDecimal getVolume() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.vehicles.volume_unit</code>.
     */
    public void setVolumeUnit(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.vehicles.volume_unit</code>.
     */
    public Integer getVolumeUnit() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.vehicles.eco</code>.
     */
    public void setEco(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.vehicles.eco</code>.
     */
    public Integer getEco() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.vehicles.alias</code>.
     */
    public void setAlias(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.vehicles.alias</code>.
     */
    public String getAlias() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.vehicles.created_user</code>.
     */
    public void setCreatedUser(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.vehicles.created_user</code>.
     */
    public Long getCreatedUser() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.vehicles.status</code>.
     */
    public void setStatus(VehStatus value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.vehicles.status</code>.
     */
    public VehStatus getStatus() {
        return (VehStatus) get(16);
    }

    /**
     * Setter for <code>public.vehicles.planned_waypoint_id</code>.
     */
    public void setPlannedWaypointId(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.vehicles.planned_waypoint_id</code>.
     */
    public Long getPlannedWaypointId() {
        return (Long) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, Long, String, Integer, Timestamp, Timestamp, String, String, BigDecimal, Integer, BigDecimal, Integer, Integer, String, Long, VehStatus, Long> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, Long, String, Integer, Timestamp, Timestamp, String, String, BigDecimal, Integer, BigDecimal, Integer, Integer, String, Long, VehStatus, Long> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Vehicles.VEHICLES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Vehicles.VEHICLES.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Vehicles.VEHICLES.BRANCH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Vehicles.VEHICLES.REG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Vehicles.VEHICLES.TRAILER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Vehicles.VEHICLES.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Vehicles.VEHICLES.MODIFIED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Vehicles.VEHICLES.MODIFIED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Vehicles.VEHICLES.SHIPPING_STATUS_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return Vehicles.VEHICLES.CAPACITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Vehicles.VEHICLES.CAPACITY_UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return Vehicles.VEHICLES.VOLUME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Vehicles.VEHICLES.VOLUME_UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Vehicles.VEHICLES.ECO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Vehicles.VEHICLES.ALIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return Vehicles.VEHICLES.CREATED_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<VehStatus> field17() {
        return Vehicles.VEHICLES.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return Vehicles.VEHICLES.PLANNED_WAYPOINT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getBranchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTrailerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getModifiedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getShippingStatusCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getCapacity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getCapacityUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getVolume();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getVolumeUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getEco();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getCreatedUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehStatus value17() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getPlannedWaypointId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value2(Long value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value3(Long value) {
        setBranchId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value4(String value) {
        setReg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value5(Integer value) {
        setTrailerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value6(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value7(Timestamp value) {
        setModifiedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value8(String value) {
        setModifiedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value9(String value) {
        setShippingStatusCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value10(BigDecimal value) {
        setCapacity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value11(Integer value) {
        setCapacityUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value12(BigDecimal value) {
        setVolume(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value13(Integer value) {
        setVolumeUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value14(Integer value) {
        setEco(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value15(String value) {
        setAlias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value16(Long value) {
        setCreatedUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value17(VehStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value18(Long value) {
        setPlannedWaypointId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord values(Long value1, Long value2, Long value3, String value4, Integer value5, Timestamp value6, Timestamp value7, String value8, String value9, BigDecimal value10, Integer value11, BigDecimal value12, Integer value13, Integer value14, String value15, Long value16, VehStatus value17, Long value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehiclesRecord
     */
    public VehiclesRecord() {
        super(Vehicles.VEHICLES);
    }

    /**
     * Create a detached, initialised VehiclesRecord
     */
    public VehiclesRecord(Long id, Long modelId, Long branchId, String reg, Integer trailerId, Timestamp createdDate, Timestamp modifiedDate, String modifiedUser, String shippingStatusCode, BigDecimal capacity, Integer capacityUnit, BigDecimal volume, Integer volumeUnit, Integer eco, String alias, Long createdUser, VehStatus status, Long plannedWaypointId) {
        super(Vehicles.VEHICLES);

        set(0, id);
        set(1, modelId);
        set(2, branchId);
        set(3, reg);
        set(4, trailerId);
        set(5, createdDate);
        set(6, modifiedDate);
        set(7, modifiedUser);
        set(8, shippingStatusCode);
        set(9, capacity);
        set(10, capacityUnit);
        set(11, volume);
        set(12, volumeUnit);
        set(13, eco);
        set(14, alias);
        set(15, createdUser);
        set(16, status);
        set(17, plannedWaypointId);
    }
}
