/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BillingContacts implements Serializable {

    private static final long serialVersionUID = -975103110;

    private Long      id;
    private Long      orgId;
    private Long      openOrgId;
    private Long      vehicleId;
    private Timestamp vehicleOpenDate;
    private Long      dealId;
    private Timestamp dealOpenDate;

    public BillingContacts() {}

    public BillingContacts(BillingContacts value) {
        this.id = value.id;
        this.orgId = value.orgId;
        this.openOrgId = value.openOrgId;
        this.vehicleId = value.vehicleId;
        this.vehicleOpenDate = value.vehicleOpenDate;
        this.dealId = value.dealId;
        this.dealOpenDate = value.dealOpenDate;
    }

    public BillingContacts(
        Long      id,
        Long      orgId,
        Long      openOrgId,
        Long      vehicleId,
        Timestamp vehicleOpenDate,
        Long      dealId,
        Timestamp dealOpenDate
    ) {
        this.id = id;
        this.orgId = orgId;
        this.openOrgId = openOrgId;
        this.vehicleId = vehicleId;
        this.vehicleOpenDate = vehicleOpenDate;
        this.dealId = dealId;
        this.dealOpenDate = dealOpenDate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrgId() {
        return this.orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public Long getOpenOrgId() {
        return this.openOrgId;
    }

    public void setOpenOrgId(Long openOrgId) {
        this.openOrgId = openOrgId;
    }

    public Long getVehicleId() {
        return this.vehicleId;
    }

    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

    public Timestamp getVehicleOpenDate() {
        return this.vehicleOpenDate;
    }

    public void setVehicleOpenDate(Timestamp vehicleOpenDate) {
        this.vehicleOpenDate = vehicleOpenDate;
    }

    public Long getDealId() {
        return this.dealId;
    }

    public void setDealId(Long dealId) {
        this.dealId = dealId;
    }

    public Timestamp getDealOpenDate() {
        return this.dealOpenDate;
    }

    public void setDealOpenDate(Timestamp dealOpenDate) {
        this.dealOpenDate = dealOpenDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BillingContacts (");

        sb.append(id);
        sb.append(", ").append(orgId);
        sb.append(", ").append(openOrgId);
        sb.append(", ").append(vehicleId);
        sb.append(", ").append(vehicleOpenDate);
        sb.append(", ").append(dealId);
        sb.append(", ").append(dealOpenDate);

        sb.append(")");
        return sb.toString();
    }
}
