/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryRegion implements Serializable {

    private static final long serialVersionUID = 352073532;

    private Integer   id;
    private Long      translationId;
    private Timestamp createdDate;
    private Timestamp modifiedDate;
    private String    createdUser;
    private String    modifiedUser;

    public CountryRegion() {}

    public CountryRegion(CountryRegion value) {
        this.id = value.id;
        this.translationId = value.translationId;
        this.createdDate = value.createdDate;
        this.modifiedDate = value.modifiedDate;
        this.createdUser = value.createdUser;
        this.modifiedUser = value.modifiedUser;
    }

    public CountryRegion(
        Integer   id,
        Long      translationId,
        Timestamp createdDate,
        Timestamp modifiedDate,
        String    createdUser,
        String    modifiedUser
    ) {
        this.id = id;
        this.translationId = translationId;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.createdUser = createdUser;
        this.modifiedUser = modifiedUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getTranslationId() {
        return this.translationId;
    }

    public void setTranslationId(Long translationId) {
        this.translationId = translationId;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    public Timestamp getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Timestamp modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public String getCreatedUser() {
        return this.createdUser;
    }

    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    public String getModifiedUser() {
        return this.modifiedUser;
    }

    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CountryRegion (");

        sb.append(id);
        sb.append(", ").append(translationId);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(modifiedUser);

        sb.append(")");
        return sb.toString();
    }
}
