/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Currencies implements Serializable {

    private static final long serialVersionUID = 696324763;

    private String  code;
    private String  name;
    private Long    translationId;
    private Boolean inUse;

    public Currencies() {}

    public Currencies(Currencies value) {
        this.code = value.code;
        this.name = value.name;
        this.translationId = value.translationId;
        this.inUse = value.inUse;
    }

    public Currencies(
        String  code,
        String  name,
        Long    translationId,
        Boolean inUse
    ) {
        this.code = code;
        this.name = name;
        this.translationId = translationId;
        this.inUse = inUse;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getTranslationId() {
        return this.translationId;
    }

    public void setTranslationId(Long translationId) {
        this.translationId = translationId;
    }

    public Boolean getInUse() {
        return this.inUse;
    }

    public void setInUse(Boolean inUse) {
        this.inUse = inUse;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Currencies (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(translationId);
        sb.append(", ").append(inUse);

        sb.append(")");
        return sb.toString();
    }
}
