/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.pojos;


import com.nayanzin.springbootjooq.db.public_.enums.ModerationStatus;
import com.nayanzin.springbootjooq.db.public_.enums.OrgType;
import com.nayanzin.springbootjooq.db.public_.enums.PreferredWaypoints;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizations implements Serializable {

    private static final long serialVersionUID = 529734225;

    private Long               id;
    private String             name;
    private String             countryCode;
    private Timestamp          createdDate;
    private Timestamp          modifiedDate;
    private String             createdUser;
    private String             modifiedUser;
    private ModerationStatus   moderationStatus;
    private String             description;
    private OrgType            orgType;
    private PreferredWaypoints preferredWaypoints;
    private String             preferredCountries;
    private String             individualGroups;

    public Organizations() {}

    public Organizations(Organizations value) {
        this.id = value.id;
        this.name = value.name;
        this.countryCode = value.countryCode;
        this.createdDate = value.createdDate;
        this.modifiedDate = value.modifiedDate;
        this.createdUser = value.createdUser;
        this.modifiedUser = value.modifiedUser;
        this.moderationStatus = value.moderationStatus;
        this.description = value.description;
        this.orgType = value.orgType;
        this.preferredWaypoints = value.preferredWaypoints;
        this.preferredCountries = value.preferredCountries;
        this.individualGroups = value.individualGroups;
    }

    public Organizations(
        Long               id,
        String             name,
        String             countryCode,
        Timestamp          createdDate,
        Timestamp          modifiedDate,
        String             createdUser,
        String             modifiedUser,
        ModerationStatus   moderationStatus,
        String             description,
        OrgType            orgType,
        PreferredWaypoints preferredWaypoints,
        String             preferredCountries,
        String             individualGroups
    ) {
        this.id = id;
        this.name = name;
        this.countryCode = countryCode;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.createdUser = createdUser;
        this.modifiedUser = modifiedUser;
        this.moderationStatus = moderationStatus;
        this.description = description;
        this.orgType = orgType;
        this.preferredWaypoints = preferredWaypoints;
        this.preferredCountries = preferredCountries;
        this.individualGroups = individualGroups;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    public Timestamp getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Timestamp modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public String getCreatedUser() {
        return this.createdUser;
    }

    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    public String getModifiedUser() {
        return this.modifiedUser;
    }

    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser;
    }

    public ModerationStatus getModerationStatus() {
        return this.moderationStatus;
    }

    public void setModerationStatus(ModerationStatus moderationStatus) {
        this.moderationStatus = moderationStatus;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public OrgType getOrgType() {
        return this.orgType;
    }

    public void setOrgType(OrgType orgType) {
        this.orgType = orgType;
    }

    public PreferredWaypoints getPreferredWaypoints() {
        return this.preferredWaypoints;
    }

    public void setPreferredWaypoints(PreferredWaypoints preferredWaypoints) {
        this.preferredWaypoints = preferredWaypoints;
    }

    public String getPreferredCountries() {
        return this.preferredCountries;
    }

    public void setPreferredCountries(String preferredCountries) {
        this.preferredCountries = preferredCountries;
    }

    public String getIndividualGroups() {
        return this.individualGroups;
    }

    public void setIndividualGroups(String individualGroups) {
        this.individualGroups = individualGroups;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organizations (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(countryCode);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(createdUser);
        sb.append(", ").append(modifiedUser);
        sb.append(", ").append(moderationStatus);
        sb.append(", ").append(description);
        sb.append(", ").append(orgType);
        sb.append(", ").append(preferredWaypoints);
        sb.append(", ").append(preferredCountries);
        sb.append(", ").append(individualGroups);

        sb.append(")");
        return sb.toString();
    }
}
