/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ratings implements Serializable {

    private static final long serialVersionUID = -1178629086;

    private Long      id;
    private Long      ratedOrgId;
    private Long      raterOrgId;
    private Short     mark;
    private String    comment;
    private Boolean   anonymous;
    private Boolean   showCargo;
    private Timestamp createdDate;
    private Long      dealId;
    private Long      createdUser;

    public Ratings() {}

    public Ratings(Ratings value) {
        this.id = value.id;
        this.ratedOrgId = value.ratedOrgId;
        this.raterOrgId = value.raterOrgId;
        this.mark = value.mark;
        this.comment = value.comment;
        this.anonymous = value.anonymous;
        this.showCargo = value.showCargo;
        this.createdDate = value.createdDate;
        this.dealId = value.dealId;
        this.createdUser = value.createdUser;
    }

    public Ratings(
        Long      id,
        Long      ratedOrgId,
        Long      raterOrgId,
        Short     mark,
        String    comment,
        Boolean   anonymous,
        Boolean   showCargo,
        Timestamp createdDate,
        Long      dealId,
        Long      createdUser
    ) {
        this.id = id;
        this.ratedOrgId = ratedOrgId;
        this.raterOrgId = raterOrgId;
        this.mark = mark;
        this.comment = comment;
        this.anonymous = anonymous;
        this.showCargo = showCargo;
        this.createdDate = createdDate;
        this.dealId = dealId;
        this.createdUser = createdUser;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRatedOrgId() {
        return this.ratedOrgId;
    }

    public void setRatedOrgId(Long ratedOrgId) {
        this.ratedOrgId = ratedOrgId;
    }

    public Long getRaterOrgId() {
        return this.raterOrgId;
    }

    public void setRaterOrgId(Long raterOrgId) {
        this.raterOrgId = raterOrgId;
    }

    public Short getMark() {
        return this.mark;
    }

    public void setMark(Short mark) {
        this.mark = mark;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Boolean getAnonymous() {
        return this.anonymous;
    }

    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

    public Boolean getShowCargo() {
        return this.showCargo;
    }

    public void setShowCargo(Boolean showCargo) {
        this.showCargo = showCargo;
    }

    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    public Long getDealId() {
        return this.dealId;
    }

    public void setDealId(Long dealId) {
        this.dealId = dealId;
    }

    public Long getCreatedUser() {
        return this.createdUser;
    }

    public void setCreatedUser(Long createdUser) {
        this.createdUser = createdUser;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ratings (");

        sb.append(id);
        sb.append(", ").append(ratedOrgId);
        sb.append(", ").append(raterOrgId);
        sb.append(", ").append(mark);
        sb.append(", ").append(comment);
        sb.append(", ").append(anonymous);
        sb.append(", ").append(showCargo);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(dealId);
        sb.append(", ").append(createdUser);

        sb.append(")");
        return sb.toString();
    }
}
