/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrkAccounts implements Serializable {

    private static final long serialVersionUID = -945550230;

    private Integer id;
    private Integer systemId;
    private String  login;
    private String  password;
    private Integer status;
    private Integer orgId;
    private String  keyAccess;
    private String  imei;
    private String  clientId;
    private String  clientName;

    public TrkAccounts() {}

    public TrkAccounts(TrkAccounts value) {
        this.id = value.id;
        this.systemId = value.systemId;
        this.login = value.login;
        this.password = value.password;
        this.status = value.status;
        this.orgId = value.orgId;
        this.keyAccess = value.keyAccess;
        this.imei = value.imei;
        this.clientId = value.clientId;
        this.clientName = value.clientName;
    }

    public TrkAccounts(
        Integer id,
        Integer systemId,
        String  login,
        String  password,
        Integer status,
        Integer orgId,
        String  keyAccess,
        String  imei,
        String  clientId,
        String  clientName
    ) {
        this.id = id;
        this.systemId = systemId;
        this.login = login;
        this.password = password;
        this.status = status;
        this.orgId = orgId;
        this.keyAccess = keyAccess;
        this.imei = imei;
        this.clientId = clientId;
        this.clientName = clientName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSystemId() {
        return this.systemId;
    }

    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getOrgId() {
        return this.orgId;
    }

    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    public String getKeyAccess() {
        return this.keyAccess;
    }

    public void setKeyAccess(String keyAccess) {
        this.keyAccess = keyAccess;
    }

    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getClientId() {
        return this.clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getClientName() {
        return this.clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TrkAccounts (");

        sb.append(id);
        sb.append(", ").append(systemId);
        sb.append(", ").append(login);
        sb.append(", ").append(password);
        sb.append(", ").append(status);
        sb.append(", ").append(orgId);
        sb.append(", ").append(keyAccess);
        sb.append(", ").append(imei);
        sb.append(", ").append(clientId);
        sb.append(", ").append(clientName);

        sb.append(")");
        return sb.toString();
    }
}
