/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.information_schema.tables;


import com.nayanzin.springbootjooq.db.information_schema.InformationSchema;
import com.nayanzin.springbootjooq.db.information_schema.tables.records._PgUserMappingsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _PgUserMappings extends TableImpl<_PgUserMappingsRecord> {

    private static final long serialVersionUID = -2093900446;

    /**
     * The reference instance of <code>information_schema._pg_user_mappings</code>
     */
    public static final _PgUserMappings _PG_USER_MAPPINGS = new _PgUserMappings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<_PgUserMappingsRecord> getRecordType() {
        return _PgUserMappingsRecord.class;
    }

    /**
     * The column <code>information_schema._pg_user_mappings.oid</code>.
     */
    public final TableField<_PgUserMappingsRecord, Long> OID = createField("oid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>information_schema._pg_user_mappings.umoptions</code>.
     */
    public final TableField<_PgUserMappingsRecord, String[]> UMOPTIONS = createField("umoptions", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * The column <code>information_schema._pg_user_mappings.umuser</code>.
     */
    public final TableField<_PgUserMappingsRecord, Long> UMUSER = createField("umuser", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>information_schema._pg_user_mappings.authorization_identifier</code>.
     */
    public final TableField<_PgUserMappingsRecord, String> AUTHORIZATION_IDENTIFIER = createField("authorization_identifier", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema._pg_user_mappings.foreign_server_catalog</code>.
     */
    public final TableField<_PgUserMappingsRecord, String> FOREIGN_SERVER_CATALOG = createField("foreign_server_catalog", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema._pg_user_mappings.foreign_server_name</code>.
     */
    public final TableField<_PgUserMappingsRecord, String> FOREIGN_SERVER_NAME = createField("foreign_server_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema._pg_user_mappings.srvowner</code>.
     */
    public final TableField<_PgUserMappingsRecord, String> SRVOWNER = createField("srvowner", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>information_schema._pg_user_mappings</code> table reference
     */
    public _PgUserMappings() {
        this("_pg_user_mappings", null);
    }

    /**
     * Create an aliased <code>information_schema._pg_user_mappings</code> table reference
     */
    public _PgUserMappings(String alias) {
        this(alias, _PG_USER_MAPPINGS);
    }

    private _PgUserMappings(String alias, Table<_PgUserMappingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private _PgUserMappings(String alias, Table<_PgUserMappingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _PgUserMappings as(String alias) {
        return new _PgUserMappings(alias, this);
    }

    /**
     * Rename this table
     */
    public _PgUserMappings rename(String name) {
        return new _PgUserMappings(name, null);
    }
}
