/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.information_schema.tables;


import com.nayanzin.springbootjooq.db.information_schema.InformationSchema;
import com.nayanzin.springbootjooq.db.information_schema.tables.records.SqlPackagesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqlPackages extends TableImpl<SqlPackagesRecord> {

    private static final long serialVersionUID = -1954782169;

    /**
     * The reference instance of <code>information_schema.sql_packages</code>
     */
    public static final SqlPackages SQL_PACKAGES = new SqlPackages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SqlPackagesRecord> getRecordType() {
        return SqlPackagesRecord.class;
    }

    /**
     * The column <code>information_schema.sql_packages.feature_id</code>.
     */
    public final TableField<SqlPackagesRecord, String> FEATURE_ID = createField("feature_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema.sql_packages.feature_name</code>.
     */
    public final TableField<SqlPackagesRecord, String> FEATURE_NAME = createField("feature_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema.sql_packages.is_supported</code>.
     */
    public final TableField<SqlPackagesRecord, String> IS_SUPPORTED = createField("is_supported", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

    /**
     * The column <code>information_schema.sql_packages.is_verified_by</code>.
     */
    public final TableField<SqlPackagesRecord, String> IS_VERIFIED_BY = createField("is_verified_by", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema.sql_packages.comments</code>.
     */
    public final TableField<SqlPackagesRecord, String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>information_schema.sql_packages</code> table reference
     */
    public SqlPackages() {
        this("sql_packages", null);
    }

    /**
     * Create an aliased <code>information_schema.sql_packages</code> table reference
     */
    public SqlPackages(String alias) {
        this(alias, SQL_PACKAGES);
    }

    private SqlPackages(String alias, Table<SqlPackagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private SqlPackages(String alias, Table<SqlPackagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SqlPackages as(String alias) {
        return new SqlPackages(alias, this);
    }

    /**
     * Rename this table
     */
    public SqlPackages rename(String name) {
        return new SqlPackages(name, null);
    }
}
