/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables.records;


import com.nayanzin.springbootjooq.db.pg_catalog.tables.PgConstraint;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgConstraintRecord extends TableRecordImpl<PgConstraintRecord> {

    private static final long serialVersionUID = 441504287;

    /**
     * Setter for <code>pg_catalog.pg_constraint.conname</code>.
     */
    public void setConname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conname</code>.
     */
    public String getConname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.connamespace</code>.
     */
    public void setConnamespace(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.connamespace</code>.
     */
    public Long getConnamespace() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.contype</code>.
     */
    public void setContype(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.contype</code>.
     */
    public String getContype() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.condeferrable</code>.
     */
    public void setCondeferrable(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.condeferrable</code>.
     */
    public Boolean getCondeferrable() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.condeferred</code>.
     */
    public void setCondeferred(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.condeferred</code>.
     */
    public Boolean getCondeferred() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.convalidated</code>.
     */
    public void setConvalidated(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.convalidated</code>.
     */
    public Boolean getConvalidated() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conrelid</code>.
     */
    public void setConrelid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conrelid</code>.
     */
    public Long getConrelid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.contypid</code>.
     */
    public void setContypid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.contypid</code>.
     */
    public Long getContypid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conindid</code>.
     */
    public void setConindid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conindid</code>.
     */
    public Long getConindid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conparentid</code>.
     */
    public void setConparentid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conparentid</code>.
     */
    public Long getConparentid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.confrelid</code>.
     */
    public void setConfrelid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.confrelid</code>.
     */
    public Long getConfrelid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.confupdtype</code>.
     */
    public void setConfupdtype(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.confupdtype</code>.
     */
    public String getConfupdtype() {
        return (String) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.confdeltype</code>.
     */
    public void setConfdeltype(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.confdeltype</code>.
     */
    public String getConfdeltype() {
        return (String) get(12);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.confmatchtype</code>.
     */
    public void setConfmatchtype(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.confmatchtype</code>.
     */
    public String getConfmatchtype() {
        return (String) get(13);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conislocal</code>.
     */
    public void setConislocal(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conislocal</code>.
     */
    public Boolean getConislocal() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.coninhcount</code>.
     */
    public void setConinhcount(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.coninhcount</code>.
     */
    public Integer getConinhcount() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.connoinherit</code>.
     */
    public void setConnoinherit(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.connoinherit</code>.
     */
    public Boolean getConnoinherit() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conkey</code>.
     */
    public void setConkey(Short[] value) {
        set(17, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conkey</code>.
     */
    public Short[] getConkey() {
        return (Short[]) get(17);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.confkey</code>.
     */
    public void setConfkey(Short[] value) {
        set(18, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.confkey</code>.
     */
    public Short[] getConfkey() {
        return (Short[]) get(18);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conpfeqop</code>.
     */
    public void setConpfeqop(Long[] value) {
        set(19, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conpfeqop</code>.
     */
    public Long[] getConpfeqop() {
        return (Long[]) get(19);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conppeqop</code>.
     */
    public void setConppeqop(Long[] value) {
        set(20, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conppeqop</code>.
     */
    public Long[] getConppeqop() {
        return (Long[]) get(20);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conffeqop</code>.
     */
    public void setConffeqop(Long[] value) {
        set(21, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conffeqop</code>.
     */
    public Long[] getConffeqop() {
        return (Long[]) get(21);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conexclop</code>.
     */
    public void setConexclop(Long[] value) {
        set(22, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conexclop</code>.
     */
    public Long[] getConexclop() {
        return (Long[]) get(22);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.conbin</code>.
     */
    public void setConbin(Object value) {
        set(23, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.conbin</code>.
     */
    public Object getConbin() {
        return (Object) get(23);
    }

    /**
     * Setter for <code>pg_catalog.pg_constraint.consrc</code>.
     */
    public void setConsrc(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_constraint.consrc</code>.
     */
    public String getConsrc() {
        return (String) get(24);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgConstraintRecord
     */
    public PgConstraintRecord() {
        super(PgConstraint.PG_CONSTRAINT);
    }

    /**
     * Create a detached, initialised PgConstraintRecord
     */
    public PgConstraintRecord(String conname, Long connamespace, String contype, Boolean condeferrable, Boolean condeferred, Boolean convalidated, Long conrelid, Long contypid, Long conindid, Long conparentid, Long confrelid, String confupdtype, String confdeltype, String confmatchtype, Boolean conislocal, Integer coninhcount, Boolean connoinherit, Short[] conkey, Short[] confkey, Long[] conpfeqop, Long[] conppeqop, Long[] conffeqop, Long[] conexclop, Object conbin, String consrc) {
        super(PgConstraint.PG_CONSTRAINT);

        set(0, conname);
        set(1, connamespace);
        set(2, contype);
        set(3, condeferrable);
        set(4, condeferred);
        set(5, convalidated);
        set(6, conrelid);
        set(7, contypid);
        set(8, conindid);
        set(9, conparentid);
        set(10, confrelid);
        set(11, confupdtype);
        set(12, confdeltype);
        set(13, confmatchtype);
        set(14, conislocal);
        set(15, coninhcount);
        set(16, connoinherit);
        set(17, conkey);
        set(18, confkey);
        set(19, conpfeqop);
        set(20, conppeqop);
        set(21, conffeqop);
        set(22, conexclop);
        set(23, conbin);
        set(24, consrc);
    }
}
