/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.quartz.tables;


import com.nayanzin.springbootjooq.db.quartz.Keys;
import com.nayanzin.springbootjooq.db.quartz.Quartz;
import com.nayanzin.springbootjooq.db.quartz.tables.records.QrtzJobDetailsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzJobDetails extends TableImpl<QrtzJobDetailsRecord> {

    private static final long serialVersionUID = 1793982762;

    /**
     * The reference instance of <code>quartz.qrtz_job_details</code>
     */
    public static final QrtzJobDetails QRTZ_JOB_DETAILS = new QrtzJobDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QrtzJobDetailsRecord> getRecordType() {
        return QrtzJobDetailsRecord.class;
    }

    /**
     * The column <code>quartz.qrtz_job_details.sched_name</code>.
     */
    public final TableField<QrtzJobDetailsRecord, String> SCHED_NAME = createField("sched_name", org.jooq.impl.SQLDataType.VARCHAR.length(120).nullable(false), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.job_name</code>.
     */
    public final TableField<QrtzJobDetailsRecord, String> JOB_NAME = createField("job_name", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.job_group</code>.
     */
    public final TableField<QrtzJobDetailsRecord, String> JOB_GROUP = createField("job_group", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.description</code>.
     */
    public final TableField<QrtzJobDetailsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.job_class_name</code>.
     */
    public final TableField<QrtzJobDetailsRecord, String> JOB_CLASS_NAME = createField("job_class_name", org.jooq.impl.SQLDataType.VARCHAR.length(250).nullable(false), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.is_durable</code>.
     */
    public final TableField<QrtzJobDetailsRecord, Boolean> IS_DURABLE = createField("is_durable", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.is_nonconcurrent</code>.
     */
    public final TableField<QrtzJobDetailsRecord, Boolean> IS_NONCONCURRENT = createField("is_nonconcurrent", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.is_update_data</code>.
     */
    public final TableField<QrtzJobDetailsRecord, Boolean> IS_UPDATE_DATA = createField("is_update_data", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.requests_recovery</code>.
     */
    public final TableField<QrtzJobDetailsRecord, Boolean> REQUESTS_RECOVERY = createField("requests_recovery", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>quartz.qrtz_job_details.job_data</code>.
     */
    public final TableField<QrtzJobDetailsRecord, byte[]> JOB_DATA = createField("job_data", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * Create a <code>quartz.qrtz_job_details</code> table reference
     */
    public QrtzJobDetails() {
        this("qrtz_job_details", null);
    }

    /**
     * Create an aliased <code>quartz.qrtz_job_details</code> table reference
     */
    public QrtzJobDetails(String alias) {
        this(alias, QRTZ_JOB_DETAILS);
    }

    private QrtzJobDetails(String alias, Table<QrtzJobDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private QrtzJobDetails(String alias, Table<QrtzJobDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Quartz.QUARTZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QrtzJobDetailsRecord> getPrimaryKey() {
        return Keys.QRTZ_JOB_DETAILS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QrtzJobDetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<QrtzJobDetailsRecord>>asList(Keys.QRTZ_JOB_DETAILS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QrtzJobDetails as(String alias) {
        return new QrtzJobDetails(alias, this);
    }

    /**
     * Rename this table
     */
    public QrtzJobDetails rename(String name) {
        return new QrtzJobDetails(name, null);
    }
}
