/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables;


import com.nayanzin.springbootjooq.db.pg_catalog.PgCatalog;
import com.nayanzin.springbootjooq.db.pg_catalog.tables.records.PgDescriptionRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgDescription extends TableImpl<PgDescriptionRecord> {

    private static final long serialVersionUID = -343987081;

    /**
     * The reference instance of <code>pg_catalog.pg_description</code>
     */
    public static final PgDescription PG_DESCRIPTION = new PgDescription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgDescriptionRecord> getRecordType() {
        return PgDescriptionRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_description.objoid</code>.
     */
    public final TableField<PgDescriptionRecord, Long> OBJOID = createField("objoid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_description.classoid</code>.
     */
    public final TableField<PgDescriptionRecord, Long> CLASSOID = createField("classoid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_description.objsubid</code>.
     */
    public final TableField<PgDescriptionRecord, Integer> OBJSUBID = createField("objsubid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_description.description</code>.
     */
    public final TableField<PgDescriptionRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>pg_catalog.pg_description</code> table reference
     */
    public PgDescription() {
        this("pg_description", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_description</code> table reference
     */
    public PgDescription(String alias) {
        this(alias, PG_DESCRIPTION);
    }

    private PgDescription(String alias, Table<PgDescriptionRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgDescription(String alias, Table<PgDescriptionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgDescription as(String alias) {
        return new PgDescription(alias, this);
    }

    /**
     * Rename this table
     */
    public PgDescription rename(String name) {
        return new PgDescription(name, null);
    }
}
