/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables;


import com.nayanzin.springbootjooq.db.pg_catalog.PgCatalog;
import com.nayanzin.springbootjooq.db.pg_catalog.tables.records.PgGroupRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgGroup extends TableImpl<PgGroupRecord> {

    private static final long serialVersionUID = -2139927553;

    /**
     * The reference instance of <code>pg_catalog.pg_group</code>
     */
    public static final PgGroup PG_GROUP = new PgGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgGroupRecord> getRecordType() {
        return PgGroupRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_group.groname</code>.
     */
    public final TableField<PgGroupRecord, String> GRONAME = createField("groname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>pg_catalog.pg_group.grosysid</code>.
     */
    public final TableField<PgGroupRecord, Long> GROSYSID = createField("grosysid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_group.grolist</code>.
     */
    public final TableField<PgGroupRecord, Long[]> GROLIST = createField("grolist", org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * Create a <code>pg_catalog.pg_group</code> table reference
     */
    public PgGroup() {
        this("pg_group", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_group</code> table reference
     */
    public PgGroup(String alias) {
        this(alias, PG_GROUP);
    }

    private PgGroup(String alias, Table<PgGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgGroup(String alias, Table<PgGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgGroup as(String alias) {
        return new PgGroup(alias, this);
    }

    /**
     * Rename this table
     */
    public PgGroup rename(String name) {
        return new PgGroup(name, null);
    }
}
