/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables;


import com.nayanzin.springbootjooq.db.pg_catalog.PgCatalog;
import com.nayanzin.springbootjooq.db.pg_catalog.tables.records.PgLanguageRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgLanguage extends TableImpl<PgLanguageRecord> {

    private static final long serialVersionUID = 1609094962;

    /**
     * The reference instance of <code>pg_catalog.pg_language</code>
     */
    public static final PgLanguage PG_LANGUAGE = new PgLanguage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgLanguageRecord> getRecordType() {
        return PgLanguageRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_language.lanname</code>.
     */
    public final TableField<PgLanguageRecord, String> LANNAME = createField("lanname", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_language.lanowner</code>.
     */
    public final TableField<PgLanguageRecord, Long> LANOWNER = createField("lanowner", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_language.lanispl</code>.
     */
    public final TableField<PgLanguageRecord, Boolean> LANISPL = createField("lanispl", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_language.lanpltrusted</code>.
     */
    public final TableField<PgLanguageRecord, Boolean> LANPLTRUSTED = createField("lanpltrusted", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_language.lanplcallfoid</code>.
     */
    public final TableField<PgLanguageRecord, Long> LANPLCALLFOID = createField("lanplcallfoid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_language.laninline</code>.
     */
    public final TableField<PgLanguageRecord, Long> LANINLINE = createField("laninline", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_language.lanvalidator</code>.
     */
    public final TableField<PgLanguageRecord, Long> LANVALIDATOR = createField("lanvalidator", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_language.lanacl</code>.
     */
    public final TableField<PgLanguageRecord, String[]> LANACL = createField("lanacl", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * Create a <code>pg_catalog.pg_language</code> table reference
     */
    public PgLanguage() {
        this("pg_language", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_language</code> table reference
     */
    public PgLanguage(String alias) {
        this(alias, PG_LANGUAGE);
    }

    private PgLanguage(String alias, Table<PgLanguageRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgLanguage(String alias, Table<PgLanguageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgLanguage as(String alias) {
        return new PgLanguage(alias, this);
    }

    /**
     * Rename this table
     */
    public PgLanguage rename(String name) {
        return new PgLanguage(name, null);
    }
}
