/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables;


import com.nayanzin.springbootjooq.db.pg_catalog.PgCatalog;
import com.nayanzin.springbootjooq.db.pg_catalog.tables.records.PgPublicationRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPublication extends TableImpl<PgPublicationRecord> {

    private static final long serialVersionUID = -926522591;

    /**
     * The reference instance of <code>pg_catalog.pg_publication</code>
     */
    public static final PgPublication PG_PUBLICATION = new PgPublication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgPublicationRecord> getRecordType() {
        return PgPublicationRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_publication.pubname</code>.
     */
    public final TableField<PgPublicationRecord, String> PUBNAME = createField("pubname", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_publication.pubowner</code>.
     */
    public final TableField<PgPublicationRecord, Long> PUBOWNER = createField("pubowner", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_publication.puballtables</code>.
     */
    public final TableField<PgPublicationRecord, Boolean> PUBALLTABLES = createField("puballtables", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_publication.pubinsert</code>.
     */
    public final TableField<PgPublicationRecord, Boolean> PUBINSERT = createField("pubinsert", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_publication.pubupdate</code>.
     */
    public final TableField<PgPublicationRecord, Boolean> PUBUPDATE = createField("pubupdate", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_publication.pubdelete</code>.
     */
    public final TableField<PgPublicationRecord, Boolean> PUBDELETE = createField("pubdelete", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_publication.pubtruncate</code>.
     */
    public final TableField<PgPublicationRecord, Boolean> PUBTRUNCATE = createField("pubtruncate", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>pg_catalog.pg_publication</code> table reference
     */
    public PgPublication() {
        this("pg_publication", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_publication</code> table reference
     */
    public PgPublication(String alias) {
        this(alias, PG_PUBLICATION);
    }

    private PgPublication(String alias, Table<PgPublicationRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgPublication(String alias, Table<PgPublicationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublication as(String alias) {
        return new PgPublication(alias, this);
    }

    /**
     * Rename this table
     */
    public PgPublication rename(String name) {
        return new PgPublication(name, null);
    }
}
