/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables;


import com.nayanzin.springbootjooq.db.pg_catalog.PgCatalog;
import com.nayanzin.springbootjooq.db.pg_catalog.tables.records.PgRewriteRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgRewrite extends TableImpl<PgRewriteRecord> {

    private static final long serialVersionUID = -44056757;

    /**
     * The reference instance of <code>pg_catalog.pg_rewrite</code>
     */
    public static final PgRewrite PG_REWRITE = new PgRewrite();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgRewriteRecord> getRecordType() {
        return PgRewriteRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_rewrite.rulename</code>.
     */
    public final TableField<PgRewriteRecord, String> RULENAME = createField("rulename", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_rewrite.ev_class</code>.
     */
    public final TableField<PgRewriteRecord, Long> EV_CLASS = createField("ev_class", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_rewrite.ev_type</code>.
     */
    public final TableField<PgRewriteRecord, String> EV_TYPE = createField("ev_type", org.jooq.impl.SQLDataType.CHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_rewrite.ev_enabled</code>.
     */
    public final TableField<PgRewriteRecord, String> EV_ENABLED = createField("ev_enabled", org.jooq.impl.SQLDataType.CHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_rewrite.is_instead</code>.
     */
    public final TableField<PgRewriteRecord, Boolean> IS_INSTEAD = createField("is_instead", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_rewrite.ev_qual</code>.
     */
    public final TableField<PgRewriteRecord, Object> EV_QUAL = createField("ev_qual", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_node_tree"), this, "");

    /**
     * The column <code>pg_catalog.pg_rewrite.ev_action</code>.
     */
    public final TableField<PgRewriteRecord, Object> EV_ACTION = createField("ev_action", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_node_tree"), this, "");

    /**
     * Create a <code>pg_catalog.pg_rewrite</code> table reference
     */
    public PgRewrite() {
        this("pg_rewrite", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_rewrite</code> table reference
     */
    public PgRewrite(String alias) {
        this(alias, PG_REWRITE);
    }

    private PgRewrite(String alias, Table<PgRewriteRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgRewrite(String alias, Table<PgRewriteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewrite as(String alias) {
        return new PgRewrite(alias, this);
    }

    /**
     * Rename this table
     */
    public PgRewrite rename(String name) {
        return new PgRewrite(name, null);
    }
}
