/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables;


import com.nayanzin.springbootjooq.db.pg_catalog.PgCatalog;
import com.nayanzin.springbootjooq.db.pg_catalog.tables.records.PgStatisticExtRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatisticExt extends TableImpl<PgStatisticExtRecord> {

    private static final long serialVersionUID = -2112014797;

    /**
     * The reference instance of <code>pg_catalog.pg_statistic_ext</code>
     */
    public static final PgStatisticExt PG_STATISTIC_EXT = new PgStatisticExt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgStatisticExtRecord> getRecordType() {
        return PgStatisticExtRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_statistic_ext.stxrelid</code>.
     */
    public final TableField<PgStatisticExtRecord, Long> STXRELID = createField("stxrelid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext.stxname</code>.
     */
    public final TableField<PgStatisticExtRecord, String> STXNAME = createField("stxname", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext.stxnamespace</code>.
     */
    public final TableField<PgStatisticExtRecord, Long> STXNAMESPACE = createField("stxnamespace", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext.stxowner</code>.
     */
    public final TableField<PgStatisticExtRecord, Long> STXOWNER = createField("stxowner", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext.stxkeys</code>.
     */
    public final TableField<PgStatisticExtRecord, Object[]> STXKEYS = createField("stxkeys", org.jooq.impl.DefaultDataType.getDefaultDataType("int2vector").getArrayDataType(), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext.stxkind</code>.
     */
    public final TableField<PgStatisticExtRecord, String[]> STXKIND = createField("stxkind", org.jooq.impl.SQLDataType.CHAR.getArrayDataType(), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext.stxndistinct</code>.
     */
    public final TableField<PgStatisticExtRecord, Object> STXNDISTINCT = createField("stxndistinct", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_ndistinct"), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext.stxdependencies</code>.
     */
    public final TableField<PgStatisticExtRecord, Object> STXDEPENDENCIES = createField("stxdependencies", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_dependencies"), this, "");

    /**
     * Create a <code>pg_catalog.pg_statistic_ext</code> table reference
     */
    public PgStatisticExt() {
        this("pg_statistic_ext", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_statistic_ext</code> table reference
     */
    public PgStatisticExt(String alias) {
        this(alias, PG_STATISTIC_EXT);
    }

    private PgStatisticExt(String alias, Table<PgStatisticExtRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgStatisticExt(String alias, Table<PgStatisticExtRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExt as(String alias) {
        return new PgStatisticExt(alias, this);
    }

    /**
     * Rename this table
     */
    public PgStatisticExt rename(String name) {
        return new PgStatisticExt(name, null);
    }
}
