/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables;


import com.nayanzin.springbootjooq.db.pg_catalog.PgCatalog;
import com.nayanzin.springbootjooq.db.pg_catalog.tables.records.PgSubscriptionRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgSubscription extends TableImpl<PgSubscriptionRecord> {

    private static final long serialVersionUID = -266047342;

    /**
     * The reference instance of <code>pg_catalog.pg_subscription</code>
     */
    public static final PgSubscription PG_SUBSCRIPTION = new PgSubscription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgSubscriptionRecord> getRecordType() {
        return PgSubscriptionRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_subscription.subdbid</code>.
     */
    public final TableField<PgSubscriptionRecord, Long> SUBDBID = createField("subdbid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_subscription.subname</code>.
     */
    public final TableField<PgSubscriptionRecord, String> SUBNAME = createField("subname", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_subscription.subowner</code>.
     */
    public final TableField<PgSubscriptionRecord, Long> SUBOWNER = createField("subowner", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_subscription.subenabled</code>.
     */
    public final TableField<PgSubscriptionRecord, Boolean> SUBENABLED = createField("subenabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_subscription.subconninfo</code>.
     */
    public final TableField<PgSubscriptionRecord, String> SUBCONNINFO = createField("subconninfo", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_subscription.subslotname</code>.
     */
    public final TableField<PgSubscriptionRecord, String> SUBSLOTNAME = createField("subslotname", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_subscription.subsynccommit</code>.
     */
    public final TableField<PgSubscriptionRecord, String> SUBSYNCCOMMIT = createField("subsynccommit", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_subscription.subpublications</code>.
     */
    public final TableField<PgSubscriptionRecord, String[]> SUBPUBLICATIONS = createField("subpublications", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * Create a <code>pg_catalog.pg_subscription</code> table reference
     */
    public PgSubscription() {
        this("pg_subscription", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_subscription</code> table reference
     */
    public PgSubscription(String alias) {
        this(alias, PG_SUBSCRIPTION);
    }

    private PgSubscription(String alias, Table<PgSubscriptionRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgSubscription(String alias, Table<PgSubscriptionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscription as(String alias) {
        return new PgSubscription(alias, this);
    }

    /**
     * Rename this table
     */
    public PgSubscription rename(String name) {
        return new PgSubscription(name, null);
    }
}
