/**
 * This class is generated by jOOQ
 */
package com.nayanzin.springbootjooq.db.pg_catalog.tables;


import com.nayanzin.springbootjooq.db.pg_catalog.PgCatalog;
import com.nayanzin.springbootjooq.db.pg_catalog.tables.records.PgTimezoneNamesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgTimezoneNames extends TableImpl<PgTimezoneNamesRecord> {

    private static final long serialVersionUID = 1355095358;

    /**
     * The reference instance of <code>pg_catalog.pg_timezone_names</code>
     */
    public static final PgTimezoneNames PG_TIMEZONE_NAMES = new PgTimezoneNames();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgTimezoneNamesRecord> getRecordType() {
        return PgTimezoneNamesRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_timezone_names.name</code>.
     */
    public final TableField<PgTimezoneNamesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_timezone_names.abbrev</code>.
     */
    public final TableField<PgTimezoneNamesRecord, String> ABBREV = createField("abbrev", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_timezone_names.utc_offset</code>.
     */
    public final TableField<PgTimezoneNamesRecord, Object> UTC_OFFSET = createField("utc_offset", org.jooq.impl.DefaultDataType.getDefaultDataType("interval"), this, "");

    /**
     * The column <code>pg_catalog.pg_timezone_names.is_dst</code>.
     */
    public final TableField<PgTimezoneNamesRecord, Boolean> IS_DST = createField("is_dst", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>pg_catalog.pg_timezone_names</code> table reference
     */
    public PgTimezoneNames() {
        this("pg_timezone_names", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_timezone_names</code> table reference
     */
    public PgTimezoneNames(String alias) {
        this(alias, PG_TIMEZONE_NAMES);
    }

    private PgTimezoneNames(String alias, Table<PgTimezoneNamesRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgTimezoneNames(String alias, Table<PgTimezoneNamesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTimezoneNames as(String alias) {
        return new PgTimezoneNames(alias, this);
    }

    /**
     * Rename this table
     */
    public PgTimezoneNames rename(String name) {
        return new PgTimezoneNames(name, null);
    }
}
